getsentry/sentry-wizard

scripts/Electron/symbols.js
1. If on a beta version of electron the electronVersion would be
incorrect since it would remove the word "beta".
2. Symbols were now downloaded / uploaded correctly since `symbols: true` wasn't set.
3. Symbols are breakpad, not dsym
=> Fix three bugs with electron symbol uploader

lib/Steps/Integrations/Electron.ts, scripts/Electron/symbols.js
Updated integration code example due to https://github.com/getsentry/sentry-electron/pull/53:
=> ref(electron): Update Electron integration code

CHANGELOG.md, lib/Steps/Integrations/Cordova.ts
This treats a Cordova project as a single platform instead of splitting it up to ios/android.
It put the `sentry.properties` file into the project root.
=> feat: Cordova update

lib/Steps/Integrations/ReactNative.ts
This update provides support for react native version >= 0.46.X.
Ref: https://github.com/facebook/react-native/issues/14935
=> fix: support for React-Native >0.46

lib/Steps/Integrations/Cordova.ts
Searching for `*.framework` causes the script to strip archs that don't exist in other frameworks. This patch ensures only Sentry frameworks are stripped.
<details>
<summary>Example error from trying to strip other frameworks</summary>
```
Executable is /Users/johnmick/Library/Developer/Xcode/DerivedData/ThreeSixtyPlayer-fwqwnmeuamftpugdfgrgzthnieiz/Build/Products/Debug-iphoneos/ThreeSixtyPlayer.app/Frameworks/Protobuf.framework/Protobuf
Extracting arm64 from Protobuf
fatal error: lipo: input file (/Users/johnmick/Library/Developer/Xcode/DerivedData/ThreeSixtyPlayer-fwqwnmeuamftpugdfgrgzthnieiz/Build/Products/Debug-iphoneos/ThreeSixtyPlayer.app/Frameworks/Protobuf.framework/Protobuf) must be a fat file when the -extract option is specified
Merging extracted architectures: arm64
fatal …
```
=> Only strip Sentry framework from Xcode projects

lib/Steps/Integrations/Cordova.ts
Skip 'Sentry strip unused archs from Framework' with SENTRY_SKIP_FRAMEWORK_PATCH
Skip 'Upload Debug Symbols to Sentry' with SENTRY_SKIP_DSYM_UPLOAD
Refs #39
=> feat: allow short-circuiting build phases with environment variables

lib/Steps/SentryProjectSelector.ts
The UI for a project's `name` was pulled from project settings almost a year ago, in this PR: https://github.com/getsentry/sentry/pull/11986.
However, we still fill in the field at project creation time, with an title-kebab-cased version of the platform if no other name is specified (as can be seen [here](https://github.com/getsentry/sentry/blob/f3490bc05bea24451d4e3c2218cdbf17b65c0c77/src/sentry/static/sentry/app/components/createProject.jsx#L48), [here](https://github.com/getsentry/sentry/blob/f3490bc05bea24451d4e3c2218cdbf17b65c0c77/src/sentry/static/sentry/app/components/createProject.jsx#L111-L114), [here](https://github.com/getsentry/sentry/blob/f3490bc05bea24451d4e3c2218cdbf17b65c0c77/src/sentry/static/sentry/app/components/createProject.jsx#L71-L76), and …
=> fix(project selector): Use `slug` rather than `name` to identify projects

CHANGELOG.md, lib/Steps/Integrations/ReactNative.ts, package.json, yarn.lock
This adds `EXTRA_PACKAGER_ARGS` to the iOS build script to build the source map in derived data location to make sure it's not bundled with the app.
=> fix: Add react-native sourcemap output path

scripts/NextJs/next.config.js
Instead of using the reserved `package` name, the `next.config.js` is now using `packageJson`.
=> ref: Refactor of reserved varname

lib/Steps/Integrations/NextJs.ts
Direct access could create null errors if the dependency is not defined. It now uses previously defined variables, which safely access the dependency.
=> fix: Avoid reaccess with potential null errors

scripts/NextJs/next.config.js
To customize the Next.js SDK initialization, serializable values were placed in the `next.config.js`. However, to make this SDK's initialization as similar as possible to other SDKs, this changed in https://github.com/getsentry/sentry-javascript/pull/3301/commits/15e4baa8f1337ec85b6fd8c3bb481007eb380937 (there are now two config files, `sentry.client.config.js` and `sentry.server.config.js`, where the usual `Sentry.init` is placed).
=> ref(nextjs): Remove serializable configs from `next.config.js`

lib/Steps/Integrations/NextJs.ts, package.json, scripts/NextJs/next.config.js
Changing `config.devtool` in non-production environments is not recommended and [may cause regressions](https://github.com/vercel/next.js/blob/master/errors/improper-devtool.md). It's overridden by Next.js in development environments and a warning is logged in console; so to avoid this warning, `config.devtool` is only changed in non-development environments.
Links to docs (WIP) of customizing the Next.js SDK initialization have also been added.
=> fix: Only override `config.devtool` in non-production environments

lib/Steps/Integrations/NextJs.ts
https://github.com/getsentry/sentry-wizard/pull/94 performs some changes that leave a function unused. This PR removes that function (and an import that the function was using).
=> fix(nextjs): Remove unused function in the integration

.eslintrc.js, lib/Steps/Integrations/NextJs.ts, scripts/NextJs/configs/next.config.js
A handful of small changes:
- Clarify that it's the user's `package.json` version of `next` which can't be set to `latest`.
- Clarify why we have to change the version number on our plugin
- Add a link to other sentry-webpack-plugin options
- Ignore `coverage` when linting
=> chore(nextjs): Clarify messages, ignore `coverage` when linting

scripts/NextJs/configs/next.config.js, scripts/NextJs/configs/sentry.client.config.js, scripts/NextJs/configs/sentry.server.config.js
A few small last-minute changes before we release the next.js SDK:
- Pull release value from the standard `SENTRY_RELEASE` env variable
- Add note to initialization files not to set the release there but rather to use the env var, so it will get attached to source maps
- Rename method to make it clear it's a Sentry method (since all of our `next.config.js` code is going to get mixed in with whatever other `next.config.js` code the user has)
We may still want to pull much of this logic out into the SDK itself, but that's out of the scope of this PR.
=> fix(nextjs): Get release from environment

scripts/NextJs/configs/next.config.js
See detailed explanation in https://github.com/getsentry/sentry-javascript/pull/3418. TL;DR, this (together with that PR) pulls as much of the boilerplate config as possible out of `next.config.js` and into the `nextjs` SDK.
See also the [docs change](https://github.com/getsentry/sentry-docs/pull/3319/commits/06ac0bed2982b1b31a1715e4bbecf285fae2d118) corresponding to these PRs.
=> ref(nextjs): Move most config to SDK

lib/Steps/Integrations/ReactNative.ts
Fixes a regression where we removed the first argument for the Xcode unpatch method and caused the file contents to be passed instead of the filename.
Fixes #106
=> fix: Fix iOS uninstall script for React Native

lib/Steps/Integrations/BaseIntegration.ts
Fixes issues that have been reported by users about getting stuck in the platform step, or getting spammed with the same repeated platform question with then their platform selection not actually being used.
Fixes https://github.com/getsentry/sentry-wizard/issues/93,  https://github.com/getsentry/sentry-react-native/issues/1386.
Fixed by passing `_answers` to `this.shouldConfigure` in `this.shouldEmit`. Also requires `_answers` to be defined as a parameter in `shouldConfigure`.
Tested by running on a React Native sample app and a Cordova sample app.
=> fix: Fix platform selection issues and repeated prompts

lib/Steps/Integrations/ReactNative.ts
Fix missing `filename` second argument to `ReactNative._patchJS` that was causing the JS patching functionality to not work. This method is called here: https://github.com/getsentry/sentry-wizard/blob/61fdd1d26541c23dc78e20df36c40d4327dd1fb6/lib/Helper/File.ts#L20 where `match` is the filename, which should be the second parameter before the rest of the args.
Fixes https://github.com/getsentry/sentry-react-native/issues/1386#issuecomment-836311751
Reverts a change made in #72
=> fix: Fix React Native JS patching throwing errors due to incorrect argument

scripts/NextJs/configs/next.config.js
The [Sentry Webpack plugin](https://github.com/getsentry/sentry-webpack-plugin) outputs logs that may be annoying for some users, especially when running in `dryRun` mode. Adding `silent` suppresses all logs, decreasing noise to users. Docs have already been updated, in https://github.com/getsentry/sentry-docs/pull/3612.
=> ref(nextjs): Make webpack silent by default

lib/Steps/Integrations/NextJs.ts, scripts/NextJs/configs/sentry.client.config.js, scripts/NextJs/configs/sentry.server.config.js
Setting `tracesSampleRate` is key for performance monitoring. This PR adds it to the two files (`sentry.client.config.js` and `sentry.server.config.js`) initializing the Next.js SDK.
=> feat(nextjs): Add performance monitoring support to scripts

lib/Helper/File.ts
fixed writes of undefined contents when patching files.
I did not test but it seems to be a really obvious typo
Fixes #112
=> fix(file-patching): Check new contents before overwriting a file

lib/Steps/Integrations/NextJs.ts
The minimum version the Next.js SDK supports was updated in the docs, but not in the Wizard.
=> ref(nextjs): Update minimum required `next` version

CHANGELOG.md, lib/Steps/Integrations/NextJs.ts
The Wizard is currently adding every property required by Sentry CLI in `sentry.properties`, including the auth token (that shouldn't be exposed). This PR fixes this behavior by adding the auth token to `.sentryclirc` (the Sentry CLI config file), which is added to the `.gitignore`. `sentry.properties` can now be safely committed.
=> fix(nextjs): Don't expose auth token in `sentry.properties`

CHANGELOG.md, lib/Helper/SentryCli.ts, lib/Steps/Integrations/NextJs.ts
`.sentryclirc` should be an `ini` file, see [sentry-cli docs](https://docs.sentry.io/product/cli/configuration/#to-authenticate-manually). This PR fixes the formatting.
Similar PR to https://github.com/getsentry/sentry-wizard/pull/129, but wrapping the logic in a method for further usage.
Should resolve https://github.com/getsentry/sentry-javascript/issues/3968.
=> fix(nextjs): Fix `.sentryclirc` formatting in nextjs step

CHANGELOG.md
There was a missing `#`, so Craft couldn't find the version for the release.
=> meta(changelog): Update version to release `1.2.13`

scripts/NextJs/configs/_error.js
By checking the status code of the response it's possible to filter out errors for not found pages. 
I've also updated it to pass the full page context to `getInitialProps`, because otherwise this example would fail to build when converted to typescript.
=> fix(nextjs): Do not capture 404s as exceptions in `_error`

lib/Steps/Integrations/NextJs.ts
Resolves https://github.com/getsentry/sentry-wizard/issues/151.
Limiting the maximum version to the next major, to avoid users installing it and having their apps crashing if it's not supported.
=> feat(nextjs): Support Next.js v12

scripts/Electron/symbols.js
The top-level `package.json` might specify a caret range that doesn’t tell us exactly which version is installed. Look at Electron’s `package.json` instead.
=> Fix Electron version detection to use electron/package.json

lib/Steps/Integrations/NextJs.ts, scripts/NextJs/configs/_error.js
This updates the default `_error.js` page the wizard inserts into nextjs projects, to use the new `captureUnderscoreErrorException` method. It also updates the wizard helper function which checks for compatible nextjs version to also check that the SDK version is at least 7.3.0 (which is the version which added `captureUnderscoreErrorException`).
=> feat(nextjs): Use helper function in `_error.js`

.github/CODEOWNERS
This removes the codeowners file, since the wizard now falls under the purview of the frontend SDK team.
=> chore(dev): Remove codeowners file

lib/Steps/Integrations/ReactNative.ts, package.json
Fix https://github.com/getsentry/sentry-react-native/issues/2267
No need of doing https://docs.sentry.io/platforms/react-native/troubleshooting/#react-native-069-and-higher manually
We should bump a minor 1.3.0 since it's not compatible with RN < 0.69
Next: uninstall steps are broken already even for the current version of RN.
Wondering if we should get rid of the uninstall patches or not.
https://github.com/getsentry/sentry-wizard/pull/66/files Adds `EXTRA_PACKAGER_ARGS` but does not remove it during uninstall steps.
It does not unpatch the App.js that calls `Sentry.init`.
It does not delete the sentry.properties files, but just comment the fields such as `#defaults.org=`.
=> Patch React Native xcode RN 0.69

CHANGELOG.md, lib/Steps/Integrations/ReactNative.ts, package.json
Reverts getsentry/sentry-wizard#177
=> Revert "Revert "Patch React Native xcode RN 0.69""

lib/Steps/Integrations/NextJs.ts, scripts/NextJs/sentry_sample_error.js
This PR added a new page that we insert to the user's project directory during installation. This page shows a button that, once clicked, triggers an error intentionally.
This allows us to remove instructions related to sending sample errors during onboarding.
=> Add page to send onboarding sample error for Next.js

scripts/NextJs/configs/next.config.js
This adds a default value for `hideSourceMaps` to the `next.config.js` the wizard provides, so that new users will use `hidden-source-map` as their Webpack `devtool` by default in client-side builds. (This prevents browser devtools from seeing sourcemaps and therefore prevents original source code from showing up automatically in the `Sources` tab. (More information on `devtool` values can be found [here](https://webpack.js.org/configuration/devtool/).)
In conjunction with https://github.com/getsentry/sentry-javascript/pull/5649, https://github.com/getsentry/sentry-docs/pull/5464, and https://github.com/vercel/next.js/pull/40079, this is the first step in addressing the concerns raised in https://github.com/getsentry/sentry-javascript/issues/4489. See …
=> ref(nextjs): Default to hiding source maps in nextjs config

scripts/NextJs/configs/next.config.js
Ref: https://github.com/getsentry/sentry-javascript/issues/5505
As we set the default of the `autoInstrumentServerFunctions` option in the Next.js SDK to `true` in https://github.com/getsentry/sentry-javascript/pull/5919 it is no longer needed in the wizard.
=> feat(nextjs): Remove option to auto-wrap data fetchers and API routes

.craft.yml, .github/workflows/danger.yml
I don't know if the changelog was updated manually on purpose, if so let me know. Otherwise, I think the auto policy could be enabled so there is no need for PRs like this one https://github.com/getsentry/sentry-wizard/pull/202
Probably a Danger workflow should be in place otherwise release/pr without changelog could go thru.
=> chore(ci): Set changelog release policy to auto and add Danger workflow

CHANGELOG.md, lib/Steps/Integrations/NextJs.ts
Prior to that change, `@sentry/nextjs` check was never called if `next` was there, as `true || fn()` will not call `fn`.
=> fix: Always check for both, nextjs and sdk version

CHANGELOG.md, lib/Steps/Integrations/NextJs.ts
This expands the version compatibility check to include next 13, so the wizard won't yell at people who try to use it.
=> chore(nextjs): Raise nextjs version limit to include 13

CHANGELOG.md, lib/Steps/Integrations/NextJs.ts, package.json
This PR adds logic to add the `@sentry/nextjs` package if it's not installed and we either have a `yarn.lock` or `package-lock.json` file. The purpose of this change is to enable a more seamless installation process where the user doesn't require the additional step of installing `@sentry/nextjs`.
Note that this only works if there is a lock file because we need that to know which package manager to install. IMO this is probably OK. I would imagine most folks would already have that file if they are thinking about adding Sentry. I think it's unlikely that people at Sentry before even installing packages and running whatever they are using locally.
Also note that this means the `nextjs` installation works slightly differently than the other platforms. In the future, we can back propagate …
=> feat(nextjs): Add logic to add `@sentry/nextjs` if it's missing

CHANGELOG.md, README.md, bin.ts, lib/Constants.ts, lib/Helper/__tests__/SentryCli.ts, lib/Steps/OpenSentry.ts, lib/Steps/SentryProjectSelector.ts
This PR adds the `project_platform` query parameter if we set the `signup` and `integration` option when running the wizard. The purpose of this is so we can automatically create that project during signup as implemented [here](https://github.com/getsentry/getsentry/pull/9122).
Note we shouldn't merge this until all the dependent PRs are merged.
=> feat(onboarding): Add project_platform as query param if -s and -i are set

CHANGELOG.md, bin.ts, lib/Constants.ts, lib/Helper/Wizard.ts, lib/Steps/OpenSentry.ts
This PR adds an option called `--promo-code` that will pre-fill in the promo code field during signup as shown below. Note this argument only means anything if the `-s` signup argument is passed and the user is currently not logged in. We intend to use this option for specific campaigns to give folks discounts when signing up from this flow.
=> feat(promotions): promo code option

CHANGELOG.md, lib/Steps/Integrations/NextJs.ts, scripts/NextJs/configs/sentry.edge.config.js
Release [`7.31.0`](https://github.com/getsentry/sentry-javascript/releases/tag/7.31.0) of the Next.js SDK allows for error and performance instrumentation on Next.js middleware and edge routes but requires users to set up an additional `init` call in a separate file.
This PR adds that file to the templates the Wizards creates.
=> feat(nextjs): Add `sentry.edge.config.js` template

CHANGELOG.md, lib/Steps/Integrations/ReactNative.ts, lib/Steps/Integrations/__tests__/ReactNative.ts
Fixes changes in RN 0.71 and Expo since version 43.
- https://github.com/getsentry/sentry-react-native/issues/2757
- https://github.com/getsentry/sentry-wizard/issues/225
closes: https://github.com/getsentry/sentry-wizard/issues/225
=> fix(rn): Change RN Android app/build.gradle patch to match android section

CHANGELOG.md, lib/Steps/Integrations/ReactNative.ts
- context: https://github.com/getsentry/sentry-docs/pull/6490
Reading from the env was removed in `sentry-cli` v2.
- https://github.com/getsentry/sentry-cli/pull/1172/files#diff-cb8bf951f1ff97b04c8463d418fd8439d96fcd0724b12fff24b07113e6447b7dL227
=> fix(rn): Upload debug files from `$DWARF_DSYM_FOLDER_PATH` during Xcode build

lib/Helper/test-fixtures/next.config.1-merged.js, lib/Helper/test-fixtures/next.config.3-merged.js, lib/Helper/test-fixtures/next.config.4-merged.js, scripts/NextJs/configs/next.config.template.js
This PR fixes a small typo in the template for "next.config.js" which [triggers a build warning](https://github.com/getsentry/sentry-javascript/blob/master/packages/nextjs/src/config/webpack.ts#L612) that `hideSourceMaps` is unset.
=> Fix typo: `hideSourcemaps` → `hideSourceMaps`

lib/Constants.ts, lib/Helper/Package.ts, lib/Helper/PackageManager.ts, lib/Steps/ChooseIntegration.ts, lib/Steps/Integrations/NextJs.ts, lib/Steps/Integrations/ReactNative.ts, lib/Steps/Integrations/SvelteKit.ts
This PR marks the first step of adding Wizard support for the SvelteKit SDK:
* Add `SvelteKit` integration class
* SvelteKit can be selected in the integration selection prompt
* Support for `-i sveltekit` option
* Check if compatible SvelteKit version or SvelteKit SDK version is installed
* Install `@sentry/sveltekit` package if not yet installed
I'm not sure about the release cadence of the wizard. Happy to merge the steps into a branch for now and release in one go later on if we don't want the halfway-finished SvelteKit menu option to show up before it is finished. 
For now:
ref #244
=> feat(sveltekit): Add SvelteKit menu option and SDK installation

lib/Helper/Git.ts, lib/Helper/SentryCli.ts, lib/Steps/Integrations/NextJs.ts, lib/Steps/Integrations/SvelteKit.ts
This PR adds the creation of Sentry CLI config files to the SvelteKit SDK. Since the NextJS integration already does this, this PR extracts a couple of methods from the NextJS integration class to be reused for SvelteKit.
ref #244
=> feat(sveltekit): Create Sentry CLI config files

.github/workflows/release.yml
=> chore(repo): Add `merge_target` option to prepare release action

lib/Steps/Integrations/SvelteKit.ts, tsconfig.json
To respect custom hooks file locations that users can specifiy in `svelte.config.js`, we import the svelte config and use these custom paths if they're available. Otherwise, we fall back to the default paths.
This PR adjusts the `tsconfig.json` to use `node16` module resolution and code generation. This allows us to keep using tsc for the moment and preserve `await import` calls (so that they're not transpiled to `require`). I checked and it seems like the transpiled code is mostly equal to what we had before. However, reading the config will only work if users are using Node 16+. For older Node versions, the wizard will emit a warning and instruct people to use it with Node 16. IMO this is fine for the SvelteKit setup flow because SvelteKit requires Node 16 anyway as a minimum version. …
=> feat(sveltekit): Read hook file paths from `svelte.config.js`

lib/Steps/Integrations/SvelteKit.ts
This PR adds our handlers to the `handle` and `handleError` hooks in the SveltKit hooks files. I tested this with various cases of already existing, user-defined handlers. 
One limtiation:
This currently only works for arrow function exports ( `export const handleError = () => {}`). The Kit docs examples always show that handlers should be exported with arrow functions but it is possible to add normal function exports (`export function handleError(){}`). In this case we just bail out and ask users to apply our handler manually. I believe this is a rather edge-casey scenario, so IMO it's fine to just bail at the moment.
ref #244
=> feat(sveltekit): Add Sentry handlers to `handle` and `handleError` hooks 

src/sveltekit/sdk-example.ts, src/sveltekit/sdk-setup.ts, src/sveltekit/sveltekit-wizard.ts, src/templates/sveltekit-templates.ts
This PR adds the creation of a sample SvelteKit route with a page and an API route to send example frontend and backend errors (+ a transaction) to Sentry. 
Example of page in the default Sverdle app:
yes, the button might feature a nice animation ;)
ref #244
=> feat(sveltekit): Add example page creation

src/templates/nextjs-templates.ts
=> Update nextjs-templates.ts: fix spelling of Vercel

CHANGELOG.md
Before we release 3.2.0 let's polish the changelog a little
ironically:
=> chore: improve Changelog

CHANGELOG.md, lib/Steps/OpenSentry.ts
Hello :)
We are using docker without browsers and there are an error when the cli tries to open the url automatically.
https://github.com/getsentry/sentry-wizard/assets/8685132/7eafc84f-833f-466c-b66d-cd89ad9eb615
=> fix: Don't crash in environments without browser

CHANGELOG.md, package.json, yarn.lock
=> fix(sveltekit): Bump `magicast` to handle `satisfies` keyword

src/nextjs/nextjs-wizard.ts, src/sveltekit/sveltekit-wizard.ts, src/utils/clack-utils.ts
In light of #290 we want to prepare the login and project selection flow to be reusable. After going through the two JS wizards, most of the logic is already reusable so what's left are just two minor refactors which this PR addresses.
* extract the project selection step
* make the platform query param configurable (I missed this while working on SvelteKit, so this is also kind of a fix)
closes #292 
ref #290
Since this isn't user-facing:
=> ref: Extract project selection from NextJs and SvelteKit wizards

CHANGELOG.md, lib/Constants.ts, lib/Steps/ChooseIntegration.ts, lib/Steps/Integrations/SourceMapsShim.ts, lib/Steps/OpenSentry.ts
When starting the wizard without the `-i` argument, source maps should still show up as a selectable "integration" (naming isn't ideal here) in the prompt at the beginning of the wizard flow.
This PR adds this and cleans up a few `any` usages. At some point we probably want to refactor/remove this duality of old (class-based) integrations and the newer streamlined ones but I'd argue this is out of scope for now. Hence the `SourceMapsShim` class.
closes #301
=> feat(sourcemaps): Add Sourcemaps as selectable integration

lib/Steps/Integrations/SourceMapsShim.ts
Seems like we need `shouldConfigure` in the source maps shim so that the old `Step`-based wizard doesn't start its login flow but immediately redirects to our new (clack-based) wizard.
=> fix(sourcemaps): Stop redirecting to old flow when starting without `-i` flag

src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/vite.ts
Since we want this prompt in all of the source map flows we put it into the generic flow.
=> ref(sourcemaps): Extract CI environment variable prompt into generic flow

CHANGELOG.md, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/vite.ts, src/utils/clack-utils.ts
Picking up values from `.env.sentry-build-plugin` was added in the latest plugin release. Let's use it in the wizard now.
=> feat(sourcemaps): Create `.env.sentry-build-plugin` instead of `.sentryclirc` to set auth token

CHANGELOG.md, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/sentry-cli.ts, src/utils/clack-utils.ts
Resolves https://github.com/getsentry/sentry-wizard/issues/312
Adds catch-all sourcemap flow that:
- Will install `@sentry/cli`
- Asks the user to provide a path to their build artifacts
- Asks the user to verify that their build tool is generating source maps
- Will create a `package.json` script `sentry:ci` that will inject debug IDs into build artifacts and upload the artifacts
- Create a `.sentryclirc` file with an auth token so that the user can try the whole flow locally
=> feat(sourcemaps): Add setup flow for sentry-cli

CHANGELOG.md, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/webpack.ts
This PR adds a setup flow for webpack:
* install/update `@sentry/webpack-plugin`
* code snippet for `webpack.config.js`
* add `.env.sentry-build-plugin` file w/ auth token
ref #305
=> feat(sourcemaps): Add setup flow for Webpack

src/sourcemaps/sourcemaps-wizard.ts
We'll ship the first iteration without these flows so let's remove them temporarily from the tool selection step
=> ref(sourcemaps): Temporarily remove Rollup and esbuild options

CHANGELOG.md, src/sourcemaps/sourcemaps-wizard.ts
Sets the selected build tool as a tag. Small oversight from: https://github.com/getsentry/sentry-wizard/pull/318
=> feat(sourcemaps): Record in telemetry which build tool was selected

CHANGELOG.md
Updates the changelog with item from external contrib.
Danger doesn't seem to run for forks.
=> meta: Update changelog with external contribution

CHANGELOG.md, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/rollup.ts
This PR adds the source maps setup flow for rollup (with our rollup plugin). It's basically identical to the Vite/Webpack flows, just with adjusted code snippets and package installs.
(Tested w/ a node app that's bundled with rollup - works as expected)
ref #305
=> feat(sourcemaps): Add Rollup plugin flow

CHANGELOG.md, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/sentry-cli.ts, src/sourcemaps/tools/tsc.ts
Adds a separate tsc wizard to the sourcemaps flow that mostly reuses the sentry cli flow but has a separate prompt to instruct users to correctly configure their tsconfig.json.
Ref:
https://github.com/getsentry/sentry-wizard/issues/305
https://github.com/getsentry/sentry-wizard/issues/290
=> feat(sourcemaps): Add `tsc` flow

CHANGELOG.md, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/esbuild.ts
This PR adds the source maps setup flow for esbuild (with our esbuild plugin). It's basically identical to the Vite/Webpack flows, just with adjusted code snippets and package installs.
ref #305
=> feat(sourcemaps): Add setup flow for esbuild

CHANGELOG.md, src/utils/clack-utils.ts
With this PR, the wizard will automatically open the browser when asking the user to sign into Sentry. We used to have this functionality in our old wizard but removed it temporarily when switching to `clack`. Now we're gonna bring it back 🚀 
I initially wanted to switch to `open` instead of `opn` because the name of the library changed and `opn` is deprecated since a while. However, `open` is esm-only and we transpile to CJS. I tried a bunch of things and the only thing that works without changing our build setup is to dynamically import the module. This however is only available since node 14 (13) which would raise our minimum supported Node version from 6.9 to 14 :( 
So I guess the solution here is to switch to rollup and convert `open` to cjs when building... While we should …
=> feat: Open browser when logging in (sourcemaps, sveltekit, nextjs)

CHANGELOG.md, bin.ts, lib/Steps/ChooseIntegration.ts, lib/Steps/Integrations/NextJsShim.ts, lib/Steps/Integrations/SourceMapsShim.ts, lib/Steps/Integrations/SvelteKitShim.ts, src/nextjs/nextjs-wizard.ts, src/sourcemaps/sourcemaps-wizard.ts, src/sveltekit/sveltekit-wizard.ts, src/utils/clack-utils.ts, src/utils/types.ts
This PR Reintroduces support for the `--url` (`-u`) arg in the new `clack`-based wizards (Next, Sveltekit, Sourcemaps). 
This enables users to optionally specify a url when starting the wizard via the command line:
```sh
npx @sentry/wizard@latest -u https://sentry.mydomain.com -i sourcemaps
```
If this is specified, the wizards skip asking if users are using SaaS or self-hosted. However, we'll continue to validate the entered URL just like before. 
Furthermore, this PR adds some small refactors along the way to unify types and naming across the wizards. Still not a fan of the shims but we need them as long as we don't do a bigger refactor. 
ref #290
=>  fix: Support `--url` arg in NextJs, SvelteKit and Sourcemaps wizards

src/sourcemaps/utils/sdk-version.ts
Noticed that the tag for a v7 version that's not yet compatible with debug ids was off by one
=> fix(sourcemaps): Adjust initial-sdk-version tag value

bin.ts, lib/Helper/Wizard.ts, lib/Setup.ts, lib/Steps/ChooseIntegration.ts
Previously, in #331 we backfilled the `url` arg as soon as we entered the old wizard execution, which caused our clack-based flows (which were invoked by shim classes in this case) to have a pre-defined default url. Since we explicitly ask users for self-hosted/SaaS in these flows, we don't want a default value for this arg but only use it when users specified it explicitly. 
This PR reduces the backfilling to the old non-clack flows.
ref #290 
since #331 wasn't released yet:
=> fix: Backfill `url` arg only in old wizard flows

src/sourcemaps/utils/sdk-version.ts, src/utils/clack-utils.ts
This PR adds two tags to the (sourcemaps) wizard execution transaction:
- `installed-sdk` to capture which SDK is installed when the wizard was started
- `project-platform` the platform of the selected project. The API request to get the projects already returns this field, we just didn't use it before
cc @smeubank 
ref #290
not user-facing, so:
=> feat(sourcemaps|telemetry): Add tags for installed SDK and project platform

package.json, yarn.lock
Supersedes #345 
In [7.57.0](https://github.com/getsentry/sentry-javascript/releases/tag/7.57.0) we [fixed a bug](https://github.com/getsentry/sentry-javascript/pull/8357) in the `trace` function: Previously, we'd try to start a trace if the SDK wasn't enabled or tracing wasn't enabled. This bug surfaced in the wizard since we didn't always initialize the SDK (for instance, when the source maps wizard was started w/o the `-i` flag). Instead of working around this as initially attempted in #345, an SDK bump should do the trick here 😅 
More information: https://github.com/getsentry/sentry-wizard/pull/345#issuecomment-1628606624 
=> chore: Bump Sentry Node SDK to 7.57.0

bin.ts, lib/Helper/__tests__/SentryCli.ts, lib/Steps/Integrations/Apple.ts, lib/Steps/Integrations/NextJsShim.ts, lib/Steps/Integrations/SourceMapsShim.ts, lib/Steps/Integrations/SvelteKitShim.ts, src/sourcemaps/sourcemaps-wizard.ts, src/utils/types.ts
Previously, we only collected telemetry when the source maps wizard was directly started with the `-i sourcemaps` arg. This is probably the majority of cases anyway. However, for the sake of consistency, we should always collect telemetry. Therefore, this PR slightly refactors the location of the `withTelemetry` call so that we're now always using it. 
ref #290
=> ref(sourcemaps): Always collect source maps wizard telemetry

bin.ts, lib/Steps/Integrations/Apple.ts, src/apple/apple-wizard.ts
This aligns the apple wizard with the refactor of the source maps wizard in #348 where we moved the `withTelemetry` call into the wizard. 
The benefit is that we have the call in one place instead of two and that we can potentially check the `telemetryEnabled` flag whenever we need to within the wizard, as it's now part of the wizard options. 
(This is not strictly required but IMO it makes sense to keep things aligned). 
=> ref(apple): Move `withTelemetry` into `runAppleWizard`

CHANGELOG.md, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/utils/detect-tool.ts, src/sourcemaps/utils/other-wizards.ts, src/sourcemaps/utils/sdk-version.ts, src/utils/package-json.ts
This PR adds a simple auto-detection of installed build tool packages to preselect a tool selection option in the source maps wizard. Detection is performed by checking the users' `package.json` for specific packages. Either the packages of the build tool/bundler or the framework/library (Angular/CRA). If nothing is found, we fall back to the catch-all "None of the above" option which starts the Sentry CLI flow. 
ref #290
=> feat(sourcemaps): Pre-select auto-detected build tool option

CHANGELOG.md, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/sentry-cli.ts, src/utils/clack-utils.ts
Previously, our wizard implicitly assumed that users would have a CI/CD setup that builds and deploys their application. While this might be true for a lot of users, it's not always the case, so we should provide a path for users through the respective build tool flows who don't use CI. 
Therefore, this PR makes the following user-facing changes to provide a path through the wizard for non-CI users:
- Ask users if they use CI
- if yes, show CI configuration for selected tool. In the plugin case, they only need to add the auth token to their CI env. In the CLI case, they additionally need to ensure that the npm script is called.
- otherwise, no CI configuration steps are displayed and the users are just reminded that the auth token needs to be available when-/where ever they build and …
=> feat(sourcemaps): Add path for users who don't use CI

CHANGELOG.md, bin.ts, lib/Steps/Integrations/SourceMapsShim.ts
When the wizard was started with the `-i` flag, it would sometimes just keep on awaiting a promise after the `run[integration]Wizard` function returned. Seems like we broke the promise chain in #348 or sometime before that. This caused the application to appear hanging and users needing to cancel the wizard manually. 
Affected wizards.
* NextJs
* Sveltekit
* Sourcemaps
* Apple (not tested but I'm fairly certain)
This patch makes sure that the wizard exits by removing our duplicated invokation logic for the `clack`-based wizard. For the moment, we always go through the Shim classes. I'd like to refactor this eventually and get rid of the shims but for now we should fix this to unblock users.
=> fix: Ensure wizard exits after setup is completed

CHANGELOG.md, lib/Helper/Wizard.ts, src/sourcemaps/sourcemaps-wizard.ts
Seems like a check in #334 unintentionally disabled telemetry collection by default. I missed this when reviewing the PR. As a consequence of this and merging in #360, we didn't collect any telemetry data in the last 3.7.0 release. This patch removes the unnecessary check and restores telemetry collection.
Furthermore, this patch also adjusts the welcome message to no longer show the telemetry collection note in the welcome message if it is disabled.
=> fix(telemetry): Re-enable telemetry collection

CHANGELOG.md, src/utils/clack-utils.ts
We received a few internal reports about the 
```
◐  Waiting for you to log in using the link above. Once you're logged in, return to this wizard...
```
message being repeatedly printed to console while users are logging into Sentry in the browser:
This happens when the terminal window width in which the wizard is run, is smaller than the length of the message. In this case, clack seems to fail to update (turn the spinning wheel) the line and instead prints a new one. I reproduced this in a simple app and opened an [issue](https://github.com/natemoo-re/clack/issues/132) in the clack repo. Given that the repo doesn't seem too active, it's questionable though if this will be fixed.
For the meantime though, this PR reduces the message length so that our users are less likely to run into this …
=> fix(login): Avoid repeatedly printing waiting message

CHANGELOG.md, lib/Steps/ChooseIntegration.ts
Improve the wizard selection menu when starting the wizard without the `-i/--integration` arg:
Add additional checks as we have already for RN and Cordova for to pre-select other wizards if we detect a corresponding framework package:
* Electron
* NextJS
* SvelteKit
This leaves us with source maps and Apple that don't have auto-detection. Both is fine but we can probably check for apple and default to source maps(?) in the future. 
cc @brustolin if you have a free minute, how can we check for apple here?
=> feat: Autodetect more wizards

CHANGELOG.md, src/sourcemaps/utils/other-wizards.ts
This PR adds a redirection mechanism to the RN wizard if we detect an installed RN SDK and the `react-native` package in a user's `package.json`. Since for RN, we need to redirect to an old wizard flow, we can't just call `run*Wizard()` but we basically need to go through the entire wizard startup sequence again to correctly parse the CLI args. I therefore opted to just open a child process with the wizard instead. Not the prettiest solution but it seems to work well enough.  
ref https://github.com/getsentry/team-sdks/issues/16
=> ref(sourcemaps): Redirect to ReactNative wizard if RN project is detected

CHANGELOG.md, src/sveltekit/sveltekit-wizard.ts
This ensures we flush out the error once we add telemetry to sentry. Also it'll fix showing a success message when in fact we crashed.
Closes #337
=> fix(sveltekit): Abort the wizard when encountering an error

CHANGELOG.md, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/sentry-cli.ts, src/utils/package-json.ts
Our CLI-based flows currently expect users to manually call the `sentry:sourcemaps` NPM script after building and before deploying and to adjust their CI steps to acommodate for this step. This leaves room for churn/error and sometimes it's not even possibly to easily add another step (see case in #366). 
Therefore, this PR introduces an optional step in the wizard to add the `sentry:sourcemaps` script to the users' build command:
- After the `sentry:sourcemaps` script is added to users' `package.json`, the wizard will ask if the automatically want to run the script after their prod build
- The wizard then ask if the detected script is the users' prod build script and fall back to letting them choose from a list of all of their npm scripts.
- Once selected, the wizard appends the script: …
=> feat(sourcemaps): Add option to add cli npm script to build command

CHANGELOG.md, src/sourcemaps/tools/vite.ts
Previously, if we detected that a vite config file already contained Sentry code, we just bailed. This PR improves the handling here by asking users if they want to attempt the plugin insertion anyway. If yes, we try to insert the plugin and fall back to copy/paste if we fail. If no, we directly fall back to copy/paste instructions.
closes #390
=> ref(sourcemaps): Improve handling of vite config already having Sentry code

CHANGELOG.md, src/sourcemaps/tools/vite.ts, src/utils/string.ts
This PR improves one of the main reasons why our plugin injection approach currently fails. Previously, if we couldn't find a `vite.config.(js|ts|cjs|mjs)` file, we just bailed and fell back to copy paste instructions. This PR adds the following improvements:
* If we can find a vite.config file, inject the plugin (no changes here). Otherwise:
* Ask users if they have a config file. 
* If not, create a new file with a standard vite config that contains our plugin and enables source map generation.
* If this fails (i/o problems), we fall back to telling users to add a config and copy/paste code
* If yes, ask for the path to the file, validate that we can access it and inject the plugin
* Whenever we attempt plugin injection and we fail, we continue to fall back to copy/paste. I thought …
=> ref(sourcemaps): Handle no vite config found case

CHANGELOG.md, src/sourcemaps/tools/sentry-cli.ts
In the case when the user has a script called `build` we would take its value instead of its key as the name of the build command - which is, as you would have guessed it, not right.
=> fix(sentry-cli-sourcemaps): Fix writing of build command

CHANGELOG.md, lib/Steps/Integrations/Cordova.ts
By default, Sentry.CLI is bundled with Sentry Cordova and can be accessed on the following path: `plugins/sentry-cordova/node_modules/@sentry/cli/bin/sentry-cli`
The current code breaks the build if `cli.executable` is not defined on sentry.properties, so this fix sets the default value when not defined to `plugins/sentry-cordova/node_modules/@sentry/cli/bin/sentry-cli`.
EDIT:
code build with and without cli.executable:
=> fix(cordova)  iOS fails to build when sentry.cli not defined

.craft.yml, CHANGELOG.md
Adds `brew` target to automate publishing of sentry-wizard to our custom brew tap. 
There's a change on craft needs to land before this one, to make it possible accessing checksums for sentry-wizard https://github.com/getsentry/craft/pull/488
Closes #346
=> feat(craft): Add brew target on craft

CHANGELOG.md, lib/Steps/PromptForParameters.ts
When the old wizards (e.g. react native) fall back to user-input for org, project, dsn and auth token, they set the DSN as `config.dsn.secret`. AIFAICT, this is a legacy feature and all wizards only use `config.dsn.public`. As reported in #407, this caused the wizard to inject `dsn: null` into the `Sentry.init` code snippets although the DSN was entered correctly by users.
This PR fixes this behaviour by assigning the entered value to `config.dsn.public`.
(As with #409, this PR does not affect our newer, clack-based wizards)
I verified locally that this change fixes the issue. Therefore
closes #407
=> fix: Treat user-entered DSN as a public DSN

CHANGELOG.md, lib/Steps/SentryProjectSelector.ts, src/apple/apple-wizard.ts, src/remix/remix-wizard.ts, src/sveltekit/sveltekit-wizard.ts, src/utils/clack-utils.ts
This PR handles the uncaught crash when a user chose to log in but didn't yet create a project. In this case, we now print a message instructing users to create a new project first and then try running the wizard again. 
I refactored all our clack-based wizards to use the `getOrAskForProjectData` helper so that we only have to handle this once.
For the Step-based wizards, I adjusted the error message with better instructions. 
closes #400
=> fix: Handle no projects available

src/telemetry.ts
This PR sets the Sentry environment to be integration specific:
Before:
`environment: "production"`
After (for example):
`environment: "produciton-sourcemaps"`
This allows us to filter for the environment in Sentry dashboards/queries.
closes #404 
internal, so:
=> ref(telemetry): Set integration-specific `environment`

CHANGELOG.md, src/sourcemaps/tools/vite.ts, test/sourcemaps/tools/vite.test.ts
This PR fixes an oversight from #382: While we successfully added plugin insertion, we didn't enable source map generation via `build.sourcemap: true` (or `"hidden"`). This PR fixes that.
Prework to #418 since we need this there as well (albeit in a different form). 
Decided to use `recast` directly for this as `magicast` doesn't expose proper helpers. In fact, I gave up trying to work with magicast types which are super opaque due to their `ProxyfiedModule` typing. Recast gives us more freedom here and it works very well when using `recast.types.builders` to create new AST nodes.
=> fix(sourcemaps): Enable source map generation when modifying vite config

CHANGELOG.md, src/sourcemaps/tools/vite.ts, src/sourcemaps/tools/webpack.ts, src/sveltekit/sdk-setup.ts, src/utils/ast-utils.ts, src/utils/clack-utils.ts, test/sourcemaps/tools/webpack.test.ts, test/utils/ast-utils.test.ts, test/utils/clack-utils.test.ts
This PR adds automatic Webpack plugin insertion to the sourcemaps wizard's webpack flow.
This changes the webpack flow from always showing copy/paste instructions to:
* check if a webpack config exists
* if not automatically found, ask if users have one
* if not, create a new webpack config with the Sentry related code
* if yes, ask them to enter the path to their config
* modify existing config
* add require call for webpack plugin
* enable source map generation
* insert the plugin
* if any if these processes fail, we fall back to showing the copy/paste instructions
Because this is the second time that we're adding auto insertion I took the opportunity to extract some common helper functions which we can reuse in both flows and to finally add some tests. I mainly concentrated on testing …
=> feat(sourcemaps): Automatically insert Sentry Webpack plugin

CHANGELOG.md, src/android/code-tools.ts, test/android/code-tools.test.ts
Sometimes injecting the sentry import statements fails due to imports like
````java
import static a.b.c;
import x.y.z as D;
import a.b.*;
````
This PR adds support for that and some basic unit tests.
=> fix(android): Add support for unusual import statements

CHANGELOG.md, src/utils/clack-utils.ts
Small enhancement to show the list of projects in alphabetical order:
Ideally one could even type to search to filter the list, but the underlying `clack.select` doesn't seem to provide this functionality.
=> enh(wizard): sort projects in project-selection step

CHANGELOG.md, src/android/android-wizard.ts
I've had this change locally but forgot to push it before the release 🤦
=> enh(android): Show link to issues page after setup is complete

lib/Steps/ChooseIntegration.ts, src/sourcemaps/tools/tsc.ts, src/sourcemaps/tools/vite.ts, src/sourcemaps/tools/webpack.ts, src/utils/clack-utils.ts
This PR improves how we can create multi-functional code snippets that
* can be printed to the console in which case they should appear colorized (diff-like)
* can be written to a file (for example when we create a new config file)
I believe, the new `makeCodeSnippet` helper, with its formatting functions, helps us achieve still readable code snippets that can be reused with and without formatting/colorization. 
Additionally, the PR slightly adjusts the `showCopyPasteInstructions` helper to take a hint argument.
prework to #403
=> ref(wizard): Improve code snippet creation and copy paste helpers

CHANGELOG.md, src/nextjs/nextjs-wizard.ts
=> fix(nextjs): Create necessary directories in app router

CHANGELOG.md
Seems like I removed the 3.12.0 entry when rebasing a PR (must have been #434). This PR brings it back.
ironically:
=> chore: Repair changelog

CHANGELOG.md, src/sourcemaps/tools/sentry-cli.ts, src/utils/package-manager.ts, test/sourcemaps/tools/sentry-cli.test.ts
This PR fixes a bug in our Sentry-CLI flow when we printed the package manager object (introduced in #417) to the package.json instead of the package manager's run command. 
A contributing factor to this bug was that we had an eslint-ignore comment in the erroneous line that suppressed an actually correct warning. This PR removes the ignore comment and resolves both of the warnings.
Added a couple of tests to ensure this is fixed.
=> fix(sourcemaps): Write package manager command instead of object to package.json

CHANGELOG.md, src/sourcemaps/tools/tsc.ts, src/utils/ast-utils.ts, src/utils/clack-utils.ts, test/sourcemaps/tools/tsc.test.ts, test/utils/ast-utils.test.ts
This PR adds automatic adjustment of properties in `tsconfig.json` to emit source maps in the TypeScript/TSC flow of the source maps wizard. More specifically, it modifies the current source map generation flow for TSC from always printing copy/paste instructions to:
* Looking up (or asking users for) an existing tsconfig
* If it exists, automatically setting the necessariy source map properties
* If it doesn't exist, creating a new tsconfig with the options if nothing exists yet
* Showing copy/paste instructions as a fallback if something goes wrong.
`tsconfigs.json` files are not simple JSON but they can contain comments (JSON-C). To preserve as much of the original formatting as possible, I decided to parse the JSON-C file as a JS file and modifiy it with recast. 
A pure JSON object …
=> feat(sourcemaps): Automatically enable source maps generation in `tsconfig.json`

CHANGELOG.md, src/sveltekit/sdk-setup.ts, src/sveltekit/sveltekit-wizard.ts, src/sveltekit/utils.ts, src/utils/clack-utils.ts
This PR adds telemetry collection to the SvelteKit wizard. Concretely:
* Transaction and steps via `withTelemetry` and `traceStep`:
* capture minimal exceptions around known failure points
* set tags around
* Svelte and Kit versions
* Decisions to continue if precondition checks fail
* Whether files were merged (AST mods) or newly created
* Whether file modifications were successful
closes #451
=> feat(sveltekit): Add telemetry collection

CHANGELOG.md, src/sveltekit/sveltekit-wizard.ts, src/sveltekit/utils.ts
Adds a precondition check if the minimum supported sveltekit version (1.0.0) is installed. 
Note: I'd like to recommend folks to use >=1.24.0, given that it contains a fix we need in our SDK but to not make it too specific I opted for latest 1.x (also, more Kit improvements might be merged in the future). 
based on #455 until that's merged
=> ref(sveltekit): Check for minimum supported SvelteKit version

package.json, src/telemetry.ts, yarn.lock
Wanted to try out the new API. so this PR
- bumps the Node SDK to the latest version
- replaces manual `startTransaction` call with `startSpan` in `withTelemetry`
- replaces `trace` (RIP) with `startSpan` in `traceStep` (well naming is weird now 😅 )
no user facing changes, so 
=> ref(telemetry): Use new `startSpan` function

src/telemetry.ts
This PR fixes something I missed in #459: 
When using `startSpan`, the created span won't be finished if we flush inside the startSpan callback. Hence, it's not sent to Sentry, meaning erroneous transactions might be missing. This PR fixes this by moving everything around capturing exceptions and flushing _outside_ of the `startSpan` callback. Also, there's no need to update the span status on error anymore since `startSpan` does that already internally. 
=> fix(telemetry): Only flush after the root span finished

src/telemetry.ts
This PR adds progress tracking to telemetry collection to identify, where in the respective wizard users cancel or drop off. This is done by updating the value of the `progress` tag in the following cases:
* At the very beginning, `start` is set
* At the very end of a successful run, `finished` is set
* Whenever `traceStep(step, callback)` is called, the value of `step` is set.
Additionally, this PR adds an exported `updateProgress` function that can be used manually to update the progress if it makes sense. 
(This is the result of a slack thread RE progress tracking)
=> ref(telemetry): Add progress tag and `updateProgress` function

CHANGELOG.md, src/android/android-wizard.ts, src/apple/apple-wizard.ts, src/nextjs/nextjs-wizard.ts, src/remix/remix-wizard.ts, src/sourcemaps/sourcemaps-wizard.ts, src/sveltekit/sveltekit-wizard.ts, src/utils/clack-utils.ts
This PR adds a git status check to the already existing git repo existence check. If any untracked or uncommitted files are found, the wizard will ask users if they want to continue anyway. 
The git status check is performed with the [`--porcellain=v1` option](https://git-scm.com/docs/git-status#_porcelain_format_version_1), which is recommended in the git docs to be used for parsing the status. The advantage over other ways of checking for uncommitted or untracked files is that we only need one `exec` call to check for both, untracked as well as uncommitted files. 
This came up in https://github.com/getsentry/develop/pull/1030#issuecomment-1707995784 and aligns our (clack-based) wizards with the [specifications](https://develop.sentry.dev/sdk/setup-wizards/#1-check-preconditions)
=> feat(wizard): Ask for confirmation to continue if git repo is not clean

CHANGELOG.md, src/remix/remix-wizard.ts, src/remix/sdk-setup.ts
There was a bug caused by wrong parameter orders of `isV2` and `isTS` on server instrumentation step. 
Also improved Remix version checks, making them similar to svelte and next wizards.
=> fix(remix): Fix Remix version and TS checks.

CHANGELOG.md, src/sveltekit/sdk-setup.ts
Realized that we didn't log anything about modifying users' Vite config in the SvelteKit wizard. This PR fixes that. 
Also, I forgot to add the success tag - that explains why our SvelteKit dashboard only shows Vite plugin insertion fails 😅
=> ref(sveltekit): Add log for successful Vite plugin insertion

CHANGELOG.md, src/remix/codemods/handle-error.ts, src/remix/templates.ts
Fixed Remix v2's `handleError` template, that was mistakenly invoking `Sentry.captureRemixErrorBoundaryError`
Replaced it with `Sentry.captureRemixServerException`
And as it's optional, removed manual handling of non-error capturing from the template.
=> fix(remix): Use `captureRemixServerException` inside `handleError`.

CHANGELOG.md, src/remix/templates.ts
Fixed `captureRemixServerException`'s `request` parameter.
Mentioned in: https://github.com/getsentry/sentry-wizard/pull/466#discussion_r1338209336
=> fix(remix): Fix `request` arg in `handleError` template.

CHANGELOG.md
=> chore: update changelog formatting

CHANGELOG.md, src/remix/codemods/root-common.ts, src/remix/codemods/root-v1.ts, src/remix/codemods/root-v2.ts
In the current version, if there is an `ErrorBoundary` exported inside root route, Remix wizard treats it as already instrumented.
This PR adds support for auto-instrumenting existing root error boundaries.
This is also required to properly instrument Hydrogen apps.
=> fix(remix): Instrument existing root ErrorBoundary

CHANGELOG.md, src/remix/remix-wizard.ts, src/remix/sdk-setup.ts, src/remix/utils.ts
Adds support for sourcemap uploads on Hydrogen apps.
With this PR and #472, the wizard will support Hydrogen's default file/build structure.
=> feat(remix): Support sourcemap uploads of Hydrogen apps.

src/apple/apple-wizard.ts, src/utils/sentrycli-utils.ts
Added more tags to track the process.
Closes #452 
_#skip-changelog_
=> feat(Apple):More Telemetry

CHANGELOG.md, lib/Steps/ChooseIntegration.ts, src/android/android-wizard.ts, src/nextjs/nextjs-wizard.ts, src/react-native/react-native-wizard.ts, src/remix/remix-wizard.ts, src/sourcemaps/tools/nextjs.ts, src/sourcemaps/tools/sentry-cli.ts, src/sveltekit/sveltekit-wizard.ts, src/utils/clack-utils.ts
Fixes missing url, org and project in RN sentry.properties
- bug introduced in https://github.com/getsentry/sentry-wizard/pull/473
=> fix(reactnative): Save Sentry URL, Organization and Project to `sentry.properties`

CHANGELOG.md, lib/Steps/Integrations/Cordova.ts
The current script is only required when debugging on simulators, when building/deploying to real devices, the Library becomes dynamic and it's no longer required to strip the SDK.
I chose to check the `fat` library because it seems to be the safest field to be used that is language agnostic. When the file is not `fat` this strip code isn't required and so it's skipped.
Tests were done manually on a Local Sample, tested with Simulators, plugged to a real device and also deployed to the AppStore.
=> fix(Cordova)  skip dynamic libraries on Cordova

CHANGELOG.md, src/nextjs/templates.ts
Since Next.js tries to make api routes static, any api routes that are not marked as dynamic will be executed during build. This means if they throw, which our test route does, it will prevent the build from going through.
This PR sets the created route to always be dynamic.
=> fix(nextjs): Set created test route handler to always be dynamic

CHANGELOG.md, src/remix/sdk-setup.ts, src/sourcemaps/tools/sentry-cli.ts, src/utils/clack-utils.ts
After installing the `@sentry/cli` package in the CLI flow of the source maps wizard, we didn't re-read the `package.json` which overwrote the previously added package after we adjusted the build command and wrote back the stale package.json. This PR fixes that by re-reading the package.json in the build script modification function.
Also went over the other usages of package.json reading and package installing and didn't find another situation like this. Did some cleanup in Remix though.
thanks @lucas-zimerman for reporting!
closes #483
=> fix(sourcemaps): Re-read package.json after CLI install

CHANGELOG.md, src/sourcemaps/tools/sentry-cli.ts, test/sourcemaps/tools/sentry-cli.test.ts
Following up on #489 we made the same mistake twice... This PR pulls in re-reading the package.json into the build command modification function to make sure we're not passing in a stale version.
closes #483 (again)
=> fix(sourcemaps): Re-read `package.json` when modifying build command

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/nextjs/templates.ts
Following https://github.com/getsentry/sentry-docs/pull/8479 we want the wizard to provide you instructions on how to instrument React rendering errors.
=> feat(nextjs): Add instructions for custom _error page

CHANGELOG.md, src/react-native/react-native-wizard.ts, src/remix/remix-wizard.ts, src/sourcemaps/sourcemaps-wizard.ts, src/utils/clack-utils.ts, src/utils/types.ts, src/utils/url.ts
This PR updates the wizard API types to reflect recent changes.
Updates API data usage. And issue stream url creating. Adds helper function for the URL.
- Fix RN issue stream url
- Fix remix builds script -> use project slag
- Remove `project-platform` tag as the value is not send by the API
Context:
- https://github.com/getsentry/sentry/pull/59153
=> fix(wizard): Update wizard API data type and issue stream url creation

CHANGELOG.md, src/remix/remix-wizard.ts, src/remix/sdk-setup.ts
Resolves: #487
Adds Vite sourcemaps upload support to Remix wizard.
Also:
- Runs `npx run reveal` when `entry.client` / `entry.server` files do not exist in the project.
- Fixes a bug (using `project.name` instead of `project.slug`) while populating build upload script with the `project` argument.
=> feat(remix): Add Vite support.

CHANGELOG.md, src/apple/cocoapod.ts, src/react-native/react-native-wizard.ts
This PR adds dialog before running `pod install`. 
This step can take minutes and is prone to fail. This way users can avoid it and run it later, when their environment is setup for it.
=> feat(reactnative): Make `pod install` step optional

CHANGELOG.md, src/react-native/react-native-wizard.ts, src/react-native/xcode.ts, test/react-native/xcode.test.ts
Since RN SDK 5.11.0 we ship Xcode scripts which replace directly patch code into the build phases of the RN Xcode project.
This PR updates the wizard to detect the SDK version which shipps with the scripts and use them to create the Xcode build phases.
=> feat(reactnative): Use Xcode scripts bundled with Sentry RN SDK

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/nextjs/templates.ts
Adds instructions on how to add a global-error file to the App router for instrumentation.
=> feat(nextjs): Add instructions on how to add a `global-error` page to Next.js App Router

CHANGELOG.md, scripts/NextJs/configs/next.config.js, src/nextjs/templates.ts
Given we are disabling the creation of vercel cron monitors by default https://github.com/getsentry/sentry-javascript/pull/9697, let's update our onboarding to insert in `automaticVercelMonitors` as true.
Since this is being added during onboarding, we are being explicit about it being turned on. Users can easily remove this if they don't want this functionality.
=> feat(nextjs): Automatically enable vercel cron monitors

CHANGELOG.md, src/nextjs/nextjs-wizard.ts
Instructs users to restart their dev server instead of starting it. As pointed out by @ingridkindem, it wasn't entirely clear that the dev server needs to be restarted so that the next.config changes from the wizard are applied. Thanks for the suggestion!
Also made a slight change to the printing color. We wanna use `cyan` for code, file names or commands. not entire sentences.
closes https://github.com/getsentry/sentry-wizard/issues/480
=> fix(nextjs): Instruct users to restart dev server after setup

CHANGELOG.md, src/sveltekit/sveltekit-wizard.ts
Inspired by #513 and #480, this PR improves the SvelteKit wizard outro message:
- restart instead of start
- use `cyan` more sparingly
- dynamically adjust command based on detected package manager
=> ref(sveltekit): Improve outro message

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/utils/clack-utils.ts
This PR adds a prompt asking if the wizard should create an example page to test the Sentry setup.
Only if the user replies with yes, we'll create the example route and mention it in the outro.
Adding this prompt should decrease the likelihood of users accidentally comitting the example files.
Will follow up with adding the adjustment to other wizards in future PRs once we agreed on wording.
ref https://github.com/getsentry/sentry-wizard/issues/503
=> feat(nextjs): Ask for confirmation before creating example page

CHANGELOG.md, src/nextjs/templates.ts, src/sveltekit/sveltekit-wizard.ts, src/sveltekit/templates.ts
fixes https://github.com/getsentry/sentry-wizard/issues/519
We had `configureScope` and `startTransaction` calls in the example page templates. Given we've deprecated the former and will soon deprecate the other, this PR updates the templates to use the new `startSpan` API instead.
Also shows how much simpler the new API makes this example.
=> fix(nextjs,sveltekit): Replace deprecated Sentry API calls in example page templates

CHANGELOG.md, src/utils/clack-utils.ts
Seems like #405 is happening again and I have no idea what might be causing the errors here. 
Since I cannot reproduce this myself, let's log out the error so that users can report more details.
=> ref(wizard): Print error object if wizard endpoint API request failed

CHANGELOG.md, src/remix/sdk-setup.ts
This concludes removing all deprecated integration classes from the wizard with SDK version 7.100.0
=> ref(remix): Replace `BrowserTracing` with `browserTracingIntegration`

CHANGELOG.md, src/nextjs/templates.ts
Adds note about `tunnnelRotue` being incompatible with Next.js middleware.
=> feat(nextjs): Add note about `tunnelRoute` and Next.js middleware incompatibility

CHANGELOG.md, src/nextjs/templates.ts
Added comment to add spotlight in Sentry.init for next.js server config
_Note: We did not include the installation and setup of Spotlight because it is not added by default, and it is also not mandatory._
#535
=> feat(Next.js): Added Spotlight option in server config

CHANGELOG.md, src/nextjs/nextjs-wizard.ts
Once we release v8 the inserted snippet would not work in combination with the newest SDK, so we instead pin the version so that the wizard keeps working!
=> feat(nextjs): Pin installed Next.js SDK version to version 7

CHANGELOG.md, src/remix/codemods/express-server.ts
Related: https://github.com/getsentry/sentry-javascript/pull/10784
Depends on https://github.com/getsentry/sentry-javascript/pull/10811
With https://github.com/getsentry/sentry-javascript/pull/10811, we will not need to modify Vite dev-mode configuration anymore.
=> ref(remix): Remove Vite dev-mode modification step.

.github/workflows/release.yml
changes were merged into `v1` tag of the prepare release action
This reverts commit 5a5187647fc3f755b30c5044dfa60b15abd6b8ed.
=> Revert "chore(publish): Update prepare release action (#536)"

CHANGELOG.md, src/sveltekit/templates.ts
added comment to add spotlight in Sentry.init for svelteKit server hooks config
Note: We did not include the installation and setup of Spotlight because it is not added by default, and it is also not mandatory.
#535
=> feat(SvelteKit): Added Spotlight option in server config

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/nextjs/templates.ts
This PR adds a new step to the NextJS wizard where we ask if users want to register the `tunnelRoute` option. Reason: Previously we set this by default but recently learned that this causes increased Vercel bills for our users due to URL rewrites being a paid feature of Vercel.
closes #554
=> feat(nextjs): Ask users about `tunnelRoute` option

CHANGELOG.md, src/nextjs/templates.ts
The example page may have a `typescript-eslint/no-floating-promises` eslint warning/error. Since this confused a user on discord we probably want to fix it: https://discord.com/channels/621778831602221064/621778831602221072/1239945781608190022
=> feat(nextjs): Make example page resilient to `typescript-eslint/no-floating-promises`

CHANGELOG.md, src/utils/clack-utils.ts
The values of environments variables in .env files are not supposed to have quotes.
=> fix: Remove quotes around auth token in .env files

CHANGELOG.md, src/nextjs/templates.ts
`transpileClientSDK` has been removed from the next.js sentry JS SDK ([reference commit](https://github.com/getsentry/sentry-javascript/commit/7a01742ebcf5dc2b298d8e940886dea9029a6886)). 
Removes the `transpileClientSDK` property from the nextjs wizard template.
=> fix(nextjs): Remove `transpileClientSDK` from template

CHANGELOG.md, src/react-native/javascript.ts, test/react-native/javascript.test.ts
Added comment to add spotlight in Sentry.init for react-native config
Note: We did not include the installation and setup of Spotlight because it is not added by default, and it is also not mandatory.
#535
=> feat(React Native): Added Spotlight option in config

CHANGELOG.md, src/react-native/metro.ts, src/react-native/react-native-wizard.ts, src/utils/ast-utils.ts, test/react-native/metro.test.ts
Add new metro config patch released in https://github.com/getsentry/sentry-react-native/releases/tag/5.17.0
```js
const { getDefaultConfig } = require('@react-native/metro-config');
const { withSentryConfig } = require('@sentry/react-native/metro');
const config = getDefaultConfig(__dirname);
module.exports = withSentryConfig(config);
```
=> feat(rn): Add `withSentryConfig` patch for `metro.config.js`

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/nextjs/templates.ts, test/nextjs/templates.test.ts
This PR fixes a leftover from them v8 release where we replaced the `url` option with `sentryUrl` in the `withSentryConfig` options.
Also added a couple of tests for the template generation function. 
Fixes #578
=> fix(nextjs): Replace `url` with `sentryUrl` in `withSentryConfig` options

CHANGELOG.md, lib/Steps/PromptForParameters.ts
On inputting the DSN prompt, instead of the main project's URL (eg: `https://sentry.io/org/project-name`), guide the user to the `Client Keys` page (eg: `https://sentry.io/settings/projects/project-name/keys/`).
I personally encounter this while running `npx @sentry/wizard@1 -i reactNative -p ios android`
=> feat(`PromptForParameters`): user `_getDSNKeyUrl` on DSN url prompt

CHANGELOG.md, lib/Steps/PromptForParameters.ts
This PR backports #577 to version 1 of the wizard.
Created `1.x` branch from which we can cut future 1.x releases and backport fixes to.
Why create a 1.x release in 2024? Because RN documentation still references using `@sentry/wizard@1` in [the docs](https://docs.sentry.io/platforms/react-native/troubleshooting/#set-up-sdk-v4-with-react-native-069-or-higher).
Initial PR against `master` created by @hisamafahri
=> fix(step-wizards): Show correct URL when prompting DSN (Backport to v1)

package.json
Prevents NPM from assigning `latest` so that we can release a v1 version without having to release an actual new, latest version directly afterwards
=> chore(v1/publish): Set `v1` as NPM tag instead of `latest`

.github/workflows/release.yml
depends on https://github.com/getsentry/publish/pull/3950
=> chore(1.x/publish): Use `craft.yml` from 1.x branch for 1.x releases

CHANGELOG.md
Seems like the changelog policy for 1.x is different than for 3.x so this manually changes the changelog version
=> Update CHANGELOG for 1.4.1

.github/workflows/release.yml
Forgot that this needs to be set on master, not on `1.x`
=> chore(1.x/publish): Update release workflow on `master` to use craft config from merge target branch

.github/workflows/release.yml
So apparently I was wrong in #588 and manually dispatching workflows is just confusing:
* The `master` version of the workflow has a merge target input field
* But, when I run the action from another branch like `1.x`, this version of the release workflow is used, but with the GUI from the default branch.
* So you could in fact set a merge target branch as always but the `1.x` release workflow was missing this input parameter and hence didn't pass it on to `getsentry/action-prepare-release`.
This PR adds the merge target option to the `1.x` release workflow and makes sure that the input value is passed on to `getsentry/action-prepare-release`.
=> fix(v1/publish): Pass on `merge_target` property

CHANGELOG.md, src/nextjs/nextjs-wizard.ts
I've noticed that some of the generated file extensions are not consistent with the project being in JS or TS, this doesn't _actually_ impact much as next.js runs with both. 
Unsure if this is a desired change, if not, absolutely feel free to disregard and close. :)
Some minor file extension fixes for generated files on JS/TS projects.
- generated intrumention.**ts** -> instrumentation.**js**
- app/global-error.**jsx** -> app/global-error.**tsx**
- app/sentry-example-page/page.**jsx** -> app/sentry-example-page/page.**tsx**
- api/sentry-example-api/route.**js** -> api/sentry-example-api/route.**ts**
=> feat(nextjs): Detect typescript usage and emit files accordingly

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/nextjs/templates.ts
Adding a TS snippet for `GlobalError`. 
fixes https://github.com/getsentry/sentry-javascript/issues/12520
=> fix(nextjs): Fix Types of GlobalError

CHANGELOG.md, src/remix/remix-wizard.ts, src/remix/sdk-setup.ts
Updates `start` script in `package.json` with `NODE_OPTIONS="--import ..."` when the server instrumentation file is not imported inside server file (or server file does not exist).
=> feat(remix): Update `start` script for built-in Remix servers.

src/sourcemaps/sourcemaps-wizard.ts
Wizard instructions had incorrect capitalization.
=> Update correct capitalization of GitHub

CHANGELOG.md, src/nextjs/templates.ts, test/nextjs/templates.test.ts
A trailing comma is missing when selecting `selfHosted` when running the `sentry-wizard`.
=> fix(nextjs): Add trailing comma to `sentryUrl` option in `withSentryConfig` template

CHANGELOG.md, src/remix/codemods/handle-error.ts, src/remix/templates.ts
Changes the produced code for `handleError` based on the docs.
docs PR: https://github.com/getsentry/sentry-docs/pull/10597
closes: https://github.com/getsentry/sentry-javascript/issues/12785
=> fix(remix): Change `handleError` in server entry

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/nextjs/templates.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/12619
Resolves: https://github.com/getsentry/sentry-wizard/issues/633
This PR aligns the wizard to comply with NextJS's project structure.
1 - NextJS [expects the instrumentation hook either inside the root or inside the `src`  directory](https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation#:~:text=The%20instrumentation%20file%20should%20be%20in%20the%20root%20of%20your%20project%20and%20not%20inside%20the%20app%20or%20pages%20directory.%20If%20you%27re%20using%20the%20src%20folder%2C%20then%20place%20the%20file%20inside%20src%20alongside%20pages%20and%20app.). So the wizard looks for it and puts it inside `src` if it exists, and there are no `pages` or `app` folder. Otherwise it puts it on the root …
=> fix(nextjs): Update instrumentation and example creation logic for `app` or `pages` usage

CHANGELOG.md, src/nextjs/nextjs-wizard.ts
Resolves: https://github.com/getsentry/sentry-wizard/issues/627
Added support for `cjs`, `ts`, `cts` and `mts` file extensions.
=> feat(nextjs): Support all `next.config` file types.

CHANGELOG.md, src/utils/clack-utils.ts, src/utils/package-manager.ts
- Emits a `.log` file when package installation fails
- Updates the resulting log message to instruct the user to include the log file in the issue
- Adds flags to the package manager commands to ignore potential errors when running the wizard in the workspace root (noticed this to be an issue in our docs repo for example)
Relates to https://github.com/getsentry/sentry-wizard/issues/553
=> feat: Improve error logging for package installation

CHANGELOG.md, src/nextjs/templates.ts
Without this call, the following error occurs when the Error page is invoked:
> TypeError: Cannot set properties of undefined (setting '_sentryTraceData')
as described in https://github.com/getsentry/sentry-javascript/issues/5906
=> fix: Add missing `Error.getInitialProps` calls in Next.js error page snippets

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/nextjs/templates.ts, test/nextjs/templates.test.ts
Resolves: https://github.com/getsentry/sentry-wizard/issues/626
=> feat(nextjs): Prompt for `reactComponentAnnotation`.

CHANGELOG.md, lib/Steps/OpenSentry.ts, src/telemetry.ts, src/utils/clack-utils.ts
I used some dark magic debugging techniques and found that at the time the wizard was completing there were 2 open non-TTY handles:
- The telemetry flushing socket to Sentry (this one likely didn't prevent the process from exiting, at least until the flushing completed)
- A child process `'open -W https://sentry.io/account/settings/wizard/asdfadsf/'`
This PR should fix https://github.com/getsentry/sentry-wizard/issues/636 by adding the `wait: false` option to `opn`. I have no idea why this became a problem just now. Maybe with the recent bump of yargs in #625 it wasn't delegated to a non-blocking child process anymore or something (idk).
=> fix: Properly close open handles

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/nextjs/templates.ts, src/run.ts, src/sourcemaps/sourcemaps-wizard.ts, src/utils/clack-utils.ts, src/utils/types.ts, test/nextjs/templates.test.ts
Part of: https://github.com/getsentry/sentry-wizard/issues/622
This PR introduces:
- Core feature selection logic, prompts and utils
- Feature selection for NextJS wizard
- NextJS SDK feature selection for:
- Performance Monitoring
- Session Replay
- ~Spotlight (optionally generates config for it but it's still commented out like before)~ (Spotlight needs more setup and we'll do in a follow-up)
=> feat(nextjs): Add feature selection

CHANGELOG.md, src/utils/url.ts
Otherwise, the wizard would print something like
```
https://org-slug.my-sentry-instance.domain.org/issues/?project=666
```
intead of the correct one
```
https://my-sentry-instance.domain.org/organizations/org-slug/issues/?project=666
```
=> fix: Fix issue stream URL for self-hosted instances

CHANGELOG.md, src/utils/package-manager.ts, test/sourcemaps/tools/sentry-cli.test.ts
- fixes: https://github.com/getsentry/sentry-react-native/issues/4043
This PR adds support for Yarn v2+
Newer version of Yarn package manager have different behaviour and different commands, it might be better to treat them as two separate package managers. 
To correctly handle Yarn v2+ is important for React Native since the default template now uses Yarn v3.
=> feat: Detect Yarn v2+

CHANGELOG.md, src/nextjs/templates.ts
This is necessary to capture errors from nested RSCs.
=> feat(nextjs): Add `onRequestError` to `instrumentation.ts`

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/utils/clack-utils.ts
Reported by @vgrozdanic 
The `next dev` command is usually not directly used by people but rather the wrapping package.json script. So this PR now shows `<pacMan run> dev` instead of `next dev`.
=> ref(nextjs): Adjust dev server command in verification message

.github/workflows/build.yml, CHANGELOG.md, src/remix/remix-wizard.ts, src/remix/sdk-setup.ts, test/remix/client-entry.test.ts, test/remix/server-instrumentation.test.ts
Ref: https://github.com/getsentry/sentry-wizard/issues/622
=> feat(remix): Add feature selection

CHANGELOG.md, src/remix/remix-wizard.ts
Fixes: https://github.com/getsentry/sentry-wizard/issues/664
We need `.sentryclirc` file for the projects that do not use Vite, where we update the `build` script in `package.json` to use `sentry-upload-sourcemaps`. 
It is currently creating both for projects using Vite, so I moved it to where we update the build script instead.
=> fix(remix): Don't create `.sentrclirc` if project uses Vite.

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/react-native/react-native-wizard.ts, src/remix/remix-wizard.ts, src/run.ts, src/sveltekit/sveltekit-wizard.ts, src/utils/clack-utils.ts
Resolves: https://github.com/getsentry/sentry-wizard/issues/521
=> feat: Try running Prettier on exit

CHANGELOG.md, src/run.ts, src/utils/clack-utils.ts, src/utils/types.ts
Part of https://github.com/getsentry/sentry/issues/77381
Adds `--org` and `--project` parameters that narrow down options in project selection step.
If there is only one project matching the provided slugs it gets automatically selected.
If no projects match the passed slugs wizard falls back to the current behaviour
=> feat: allow passing or and project slug parameters

CHANGELOG.md, src/sveltekit/sveltekit-wizard.ts
Ref https://github.com/getsentry/sentry-wizard/issues/674
=> fix(sveltekit): Create bundler plugin env file instead of sentryclirc

CHANGELOG.md, src/sourcemaps/utils/sdk-version.ts
- closes https://github.com/getsentry/sentry/issues/77914
=> fix(check-sdk-version): add @sentry/nestjs to sentry sdk packages

CHANGELOG.md, src/android/android-wizard.ts, src/apple/apple-wizard.ts, src/nextjs/nextjs-wizard.ts, src/react-native/react-native-wizard.ts, src/remix/remix-wizard.ts, src/sourcemaps/sourcemaps-wizard.ts, src/sveltekit/sveltekit-wizard.ts, src/telemetry.ts
Adding some tags to check if (how often) users started the wizard with `--org` and/or `--project` args. 
somewhat ref #357
=> feat(telemetry): Add telemetry for org and project CLI argument usage

CHANGELOG.md, bin.ts, src/run.ts, src/telemetry.ts, src/utils/clack-utils.ts, src/utils/types.ts
Currently, our in-product onboarding shows the `--url` option because we want to skip the "Are you using Sentry.io or self-hosted" question (in-product, we already know the URL). 
From the wizard perspective, we default to the SaaS url if users don't pass a custom`--url`. However, if users pass a custom URL that is the SaaS URL we unnecessarily inject `url` params into code where it's not strictly necessary. 
The new `--saas` flag introduced in this PR will skip over the self-hosted question and if it's set to `true` assume that users are using SaaS. We can display `--saas` in the UI (for SaaS) instead of `--url`, making the snippet a bit shorter and avoiding to unnecessarily inject the `url` params into user code.
=> feat: Add `--saas` CLI arg to skip self-hosted or SaaS selection step

CHANGELOG.md, README.md, bin.ts
Adds the `project` and `org` CLI args to the `--help` message.
Also, this PR  updates the outdated readme with all current CLI args and reformats the previous CLI output into a table: [Rendered Readme](https://github.com/getsentry/sentry-wizard/blob/6b300762c8d2af0be677da4c409e3bdd5d7312e7/README.md#options). (thx AI 🙏)
=> ref: Add `--project` and `--org` args to help message and update readme

CHANGELOG.md, src/remix/sdk-example.ts
**Problem**
If a Remix project doesn't yet have a routes folder, as was the case when I followed only the initial steps of [this tutorial](https://remix.run/docs/en/main/start/tutorial), running the Sentry wizard and answering 'yes' to create a Sentry example fails to generate the example, and no feedback is provided.
**Solution**
Update the code to check whether the routes folder exists. If it doesn’t, create the folder to allow the Sentry example to be successfully generated.
**Note**
Users will still need to complete [this step](https://remix.run/docs/en/main/start/tutorial#nested-routes-and-outlets) to fully view the Sentry example. However, since the route will be created, users will at least see some feedback in the project - the new file.
closes …
=> ref(remix-wizard): Fix creation sentry example when no routes folder

CHANGELOG.md, src/utils/clack-utils.ts
Just noticed while running a repro sveltekit app in a new directory where I didn't yet initialize git that the auto-format step wasn't behaving correctly. For some reason, the child process promise when running `npx prettier ...` never resolved and I had to quit the wizard.
This PR makes a couple of changes to the prettier formatting step:
- bail if we're not in a git repo
- bail if no unchanged/untracked files are detected (could happen if users commit the changes while the wizard is runningI)
- only then prompt users if they want to run prettier
=> ref: Handle edge cases in formatting step more gracefully

CHANGELOG.md, src/apple/templates.ts, src/apple/xcode-manager.ts
This tackle an issue reported in [here](https://github.com/getsentry/sentry-docs/issues/7597), where Xcode does not work with sentry-cli installed with homebrew automatically.
=> feat(apple): Build script phase update

.github/workflows/build.yml, e2e-tests/test-applications/sveltekit-test-app/.gitignore, e2e-tests/test-applications/sveltekit-test-app/.npmrc, e2e-tests/test-applications/sveltekit-test-app/package.json, e2e-tests/test-applications/sveltekit-test-app/src/app.d.ts, e2e-tests/test-applications/sveltekit-test-app/src/app.html, e2e-tests/test-applications/sveltekit-test-app/src/lib/index.ts, e2e-tests/test-applications/sveltekit-test-app/src/routes/+page.svelte, e2e-tests/test-applications/sveltekit-test-app/svelte.config.js, e2e-tests/test-applications/sveltekit-test-app/tsconfig.json, e2e-tests/test-applications/sveltekit-test-app/vite.config.ts, e2e-tests/tests/nextjs.test.ts, e2e-tests/tests/remix.test.ts, e2e-tests/tests/sveltekit.test.ts, e2e-tests/utils/index.ts, package.json
Adds E2E tests on a plain Sveltekit app.
=> test: Add Sveltekit E2E tests

src/nextjs/nextjs-wizard.ts
Added a missing word "you" in a couple of the wizard steps because it read like a typo: `Did add the code to your app/global-error.tsx file as described above?`
=> Fix typo in a couple of steps

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/nextjs/templates.ts
This should create a little less friction in case users set `type: module` in their package json.
=> feat(nextjs): Create `next.config.mjs` when package.json has `type: "module"`

package.json, yarn.lock
Looks like one of our transitive dependencies, `plist` relied on `xmldom@0.6.0` in the past, which caused a dependabot alert in our repo. The version of plist we use [nowadays](https://github.com/TooTallNate/plist.js/blob/master/History.md#305--2022-03-23) doesn't require `xmldom` anymore at all. However, it was still mentioned in `yarn.lock` and there was an unnecessary dependency resolution in package.json. Both of which I removed.
fixes https://github.com/getsentry/sentry-wizard/security/dependabot/18
=> deps: Remove `xmldom` from lock file and resolution

package.json, yarn.lock
This PR fixes three dependabot alerts because of vulnerable ansi-regex versions. Specifically, I removed outdated ansi-regex deps by:
- bumping sentry-cli to the latest v1 version (we should have a separate convo why the wizard needs sentry-cli as a dependency)
- using [yu](https://github.com/mydea/yarn-update-dependency) to bump transitive deps of other packages
closes:
- https://github.com/getsentry/sentry-wizard/security/dependabot/14
- https://github.com/getsentry/sentry-wizard/security/dependabot/13
- https://github.com/getsentry/sentry-wizard/security/dependabot/11
=> deps: Bump ansi-regex transitive dependencies

package.json, yarn.lock
Update to latest v7 to fix https://github.com/getsentry/sentry-wizard/security/dependabot/41.
During v7, we decided to update and vendor in the `cookie` dependency, so bumping the SDK should resolve the dependabot alert.
In a next step we can bump to v8. Since we transpile to CJS, we should be fine if we init the SDK as early as possible but it requires more changes than a simple v7 bump.
=> deps: Bump @sentry/node to latest v7

e2e-tests/README.md, e2e-tests/tests/remix.test.ts, e2e-tests/tests/sveltekit.test.ts, e2e-tests/utils/index.ts
Ref: https://github.com/getsentry/sentry-wizard/pull/695#pullrequestreview-2401712903
- Adds utilities to create / modify test project files to check the behaviour when certain files exist or not.
- Applies those utilites on:
- Remix to check when there's a custom server implementation
- SvelteKit when hooks files already exist
- Adds a README for E2E tests.
=> test: Support variations in projects on E2E tests.

src/nuxt/nuxt-wizard.ts, src/run.ts, src/utils/clack-utils.ts
Tested locally with a Nuxt app. Will add tests and e2e tests https://github.com/getsentry/sentry-wizard/issues/710.
Closes: #706
=> feat(nuxt): Add Nuxt menu option and install SDK

lib/Constants.ts, src/nuxt/nuxt-wizard.ts, src/nuxt/sdk-setup.ts, src/nuxt/templates.ts, test/nuxt/templates.test.ts
Tested locally on a nuxt app with various configs. The nuxt default config is taken directly from the latest nuxt version when creating a basic project using their wizard.
Closes: #707 and #708
=> feat(nuxt): Add sdk module to nuxt config and create client and server config files

src/nuxt/nuxt-wizard.ts, src/nuxt/sdk-example.ts, src/nuxt/sdk-setup.ts, src/nuxt/templates.ts, src/nuxt/utils.ts, src/utils/clack-utils.ts
Sets up either an example page or an example vue component depending on whether the user has `<NuxtPage />` in their `app.vue`.
For users that have an `app.vue` but no `pages` route directory, adding an example page would probably be confusing as it will not visibly render anything unless `app.vue` has a `<NuxtPage/>` component.
Since we cannot reliably place <NuxtPage/> ourselves, I opted to create an example component instead for such cases.
Closes: #709
=> feat(nuxt): Add example page/component creation and final messaging

CHANGELOG.md, src/nuxt/nuxt-wizard.ts, src/nuxt/sdk-setup.ts, src/utils/clack-utils.ts
Waiting on: https://github.com/getsentry/sentry-docs/pull/12002 to update the trouble shooting url.
Closes: #726
=> feat(nuxt): Add import-in-the-middle install step when using pnpm

CHANGELOG.md, e2e-tests/tests/nuxt-3.test.ts, e2e-tests/tests/nuxt-4.test.ts, src/nuxt/nuxt-wizard.ts, src/nuxt/sdk-setup.ts, src/nuxt/templates.ts, src/nuxt/types.ts, src/nuxt/utils.ts, src/utils/clack-utils.ts, test/nuxt/templates.test.ts
We now ask where users plan to deploy their app:
For Vercel and Netlify we configure top level import of the Sentry server config file and link to docs:
For other/none we instruct people at the end to `--import` their Sentry server config file and link to docs:
This also improves the handling when a user's nuxt config can not be read. Instead of exiting the wizard, we continue and instruct people how to manually add it (already existed, but we bailed immediately after instructing).
Closes: #739
=> feat(nuxt): Add deployment-platform flow with links to docs

CHANGELOG.md, src/react-native/react-native-wizard.ts
Add warning when running on lower than supported Sentry RN SDK version.
Aborts when canceled or answered no.
This will be helpful when cutting min supported version in the future. Example min 6.X.X.
Example:
=> feat(react-native): Add minimum supported Sentry React Native SDK version detection (>=5.0.0)

CHANGELOG.md, src/utils/clack-utils.ts
Always send the current platform to the auth / project selection page.
The page will pick it up and allow creating a new project using this platform.
part of https://github.com/getsentry/sentry-wizard/issues/549
=> feat(wizard-ui): Always send platform query param

src/nextjs/nextjs-wizard.ts, src/telemetry.ts
also pass the span to the `traceStep` callback so that we can more easily interact with the step span.
=> ref(telemetry): Set tunnelroute decision as attribute and tag

e2e-tests/tests/nextjs.test.ts, e2e-tests/tests/nuxt-3.test.ts, e2e-tests/tests/nuxt-4.test.ts, e2e-tests/tests/remix.test.ts, e2e-tests/tests/sveltekit.test.ts, e2e-tests/utils/index.ts
Recently, Nuxt started using `consola` which seems to not pipe output back to stdout which in turn made our e2e tests fail.
Rather that checking arbitrary strings frameworks output at the end of their build commands, we switch to checking that the build process exited with status code 0.
The other changes in this PR come from running the formatter.
=> ref(e2e): Add `waitForStatusCode` helper and use it in `checkIfBuilds`

CHANGELOG.md, e2e-tests/utils/index.ts, src/sourcemaps/sourcemaps-wizard.ts
Remove a leftover check in the source maps wizard which is also used in the NextJS wizard that would mention `.sentryclirc` instead of `.env.sentry-build-plugins`. This was a leftover from the days where NextJS would still write `.sentryclirc`.
fixes #763
=> fix(nextjs): Mention correct local auth token file during source map generation

e2e-tests/tests/nextjs.test.ts, e2e-tests/tests/nuxt-3.test.ts, e2e-tests/tests/nuxt-4.test.ts, e2e-tests/tests/remix.test.ts, e2e-tests/tests/sveltekit.test.ts, e2e-tests/utils/index.ts, lib/Constants.ts, src/angular/angular-wizard.ts, src/run.ts, src/utils/clack-utils.ts
Supersedes #741 - Part 1
Targeted to the epic branch.
Adds Angular menu option with SDK installation
Tested locally on Angular 17/19 - and unsupported Angular version
=> feat(angular): Add Angular menu option and install SDK

src/angular/angular-wizard.ts, src/angular/codemods/app-config.ts, src/angular/sdk-setup.ts
Supersedes https://github.com/getsentry/sentry-wizard/pull/741 - Part 3
Targeted to the epic branch.
Adds Sentry setup in `app-config` files
Locally tested on Angular 17/19
=> feat(angular): Add Sentry setup in App Config

src/angular/angular-wizard.ts, src/angular/codemods/sourcemaps.ts, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/angular.ts, src/sourcemaps/tools/sentry-cli.ts
Supersedes https://github.com/getsentry/sentry-wizard/pull/741 - Part 4
Targeted to the epic branch.
Adds source map upload configuration
=> feat(angular): Configure source map upload.

README.md
- The dependency badges linking to https://david-dm.org are not rendered, and there is also no dependency information related to sentry displayed → Removed it
- Added a badge for the current CI status and the test coverage to have a direct link to Codecov.
I am open for discussion on the value of the CI status and Codecov coverage badges.
=> docs: add badges for Codecov and GitHub Actions; removed broken badges

CHANGELOG.md, package.json, src/apple/fastlane.ts, test/apple/fastfile.test.ts
- Adds unit tests to inject sentry cli into Fastfile
- Changed the import of `@clack/prompts` to fix mocking
=> test(apple): add unit tests for Fastfile injection

CHANGELOG.md, package.json, src/apple/code-tools.ts, test/apple/code-tools.test.ts, test/apple/templates.test.ts
- Adds tests for the code tools used to insert the setup snippet
- Adds more support for white-spacing in AppDelegate method detection
=> feat(apple): add extended whitespace support to AppDelegate detection; add tests for code-tools

CHANGELOG.md
just a small cleanup, removing non-user-facing entry and fixing ordering before cutting a release
=> chore: Cleanup changelog before release

CHANGELOG.md, e2e-tests/tests/remix.test.ts, src/nextjs/nextjs-wizard.ts, src/nuxt/nuxt-wizard.ts, src/remix/remix-wizard.ts, src/remix/sdk-setup.ts, src/sveltekit/sveltekit-wizard.ts, test/remix/server-instrumentation.test.ts
- Updated SDKs to v9
- Followed migration guide to remove `autoInstrumentRemix` from Remix
- Pinned nuxt wizard to v9
Closes: https://github.com/getsentry/sentry-javascript/issues/14266
=> feat: Update `nextjs`, `remix`, `sveltekit` and `nuxt` wizards to install v9

CHANGELOG.md, package.json, src/nextjs/templates.ts, src/sourcemaps/tools/nextjs.ts, test/nextjs/templates.test.ts
In v9, we removed the `hideSourceMaps` option from the nextJS SDK (`withSentryConfig` build option) because we by default set source maps to `hidden`. When we bumped the downloaded SDK version in the wizard to v9 (#794), we started installing a wizard that didn't support this option in its typedef anymore but the wizard still added it to users' code, resulting in an immediate build error during type checking. 
This PR removes the `hideSourceMaps` option from the Next config modification logic to fix this. 
Update: I created a release from this branch specifically because we couldn't release from `master` at the time of creating this PR and I wanted the fix to be released soon. That's the reason why this branch has a release bot commit and why I'm merging it without …
=> fix(nextjs): Remove outdated `hideSourceMaps` option

CHANGELOG.md, bin.ts, e2e-tests/utils/index.ts, lib/Helper/BottomBar.ts, lib/Helper/Env.ts, lib/Steps/Integrations/BaseIntegration.ts, lib/Steps/Integrations/Cordova.ts, package.json, src/apple/xcode-manager.ts, src/react-native/react-native-wizard.ts, src/react-native/uninstall.ts, src/utils/clack-utils.ts, test/apple/cocoapod.test.ts, test/apple/fastfile.test.ts, test/apple/xcode-manager.test.ts, test/utils/clack-utils.test.ts, tsconfig.build.json, types/read-env.d.ts, types/xcode.d.ts, yarn.lock
=> ref!: Follow up to Node v18 changes

CHANGELOG.md, lib/Steps/ChooseIntegration.ts, lib/Steps/Initial.ts, lib/Steps/OpenSentry.ts, src/nextjs/templates.ts, src/nuxt/sdk-setup.ts, src/react-native/expo-metro.ts, src/react-native/xcode.ts, src/run.ts, src/sourcemaps/tools/nextjs.ts, src/sourcemaps/tools/webpack.ts, src/telemetry.ts, src/utils/clack-utils.ts, tsconfig.build.json
This patch changes all dynamic requires except for a few, 'safe' cases and 'sentry/cli' related ones as it will be removed in a follow up
=> ref: No more dynamic requires

CHANGELOG.md, lib/Steps/Initial.ts, lib/Steps/Integrations/Cordova.ts, package.json, yarn.lock
We no longer require @sentry/cli to exist or to be installed so removing it.
=> ref: Remove @sentry/cli as a dependency

CHANGELOG.md, lib/Setup.ts
There was an oversight in #799 which changed how `startWizard` was called accidentally breaking all legacy wizard runs.
=> fix: Fix broken legacy wizard

CHANGELOG.md, src/telemetry.ts, src/utils/clack-utils.ts
The lookup of the `package.json` of the `@sentry/wizard` can throw when used during development outside of the repository. This is especially relevant developing the apple wizard, which is most likely in a project directory unrelated to the wizard.
The current implementation will crash the wizard, rendering it unusable. Ideally we are hard-baking the version on `yarn build`, but until then the dynamic lookup must not throw an error if the package.json is not found.
It is better to have telemetry without a node version, instead of crashing the wizard.
=> fix: Refactor the wizard version lookup to handle gracefully

.github/workflows/build.yml, .npmignore
Right now we pack the fossilized binaries to npm package on publish. This patch adds the `dist-bin` directory to `.npmignore` to make this impossible.
Follow up to #806.
=> fix: Add dist-bin binaries dir to .npmignore

.github/workflows/build.yml, package.json
No need to build (or actually double build) before running unit tests via Jest. This doesn't save a lot of CI time, due to other jobs, but we get feedback via unit tests a bit faster than before.
=> ci: Avoid building before running unit tests

lib/Steps/Integrations/Electron.ts
The recently released v6.0.0 of the Electron SDK bumps the minimum supported version of Electron to v23. 
It looks like we didn't update this for the last major version!
=> feat: Update minimum supported Electron version

CHANGELOG.md, bin.ts, lib/Steps/Initial.ts, scripts/bump-version.js, scripts/craft-pre-release.sh, src/run.ts, src/telemetry.ts, src/utils/clack-utils.ts, src/version.ts
While checking for regressions captured after the 4.x releases in Sentry, I noticed that we seem to [pick up random, incorrect](https://sentry.sentry.io/releases/?project=4505425820712960&statsPeriod=7d) `release` values instead of the wizard version in our telemetry setup. My best guess is that the previous method of preferring `process.env.npm_package_version` over reading the `package.json` somehow must have given us wrong versions in a couple of instances ( have no proof though, it could have been the package.json lookup as well). 
This likely showed a wrong version number to wizard users a startup and it reported wrong versions to Sentry.
This PR refactors how we set the wizard version by reading the version  from a `version.ts` file at build time and updating this file at release …
=> ref: Set wizard version at build time

.github/workflows/build.yml
We don't get signing secrets for external contributeros (and we shouldn't!) and we also don't really need to sign the binaries built on PRs. This PR limits signing to master branch and release/** branches.
=> ci: Limit signing to release/* and master branches

test/apple/cocoapod.test.ts, test/apple/xcode-manager.test.ts
Running the full test suite locally spawns ignored folders named `update-xcode-project-<HASH>` in the project directory. This is caused by invalid order of `mkdirSync` and `mkdtempSync`.
These generated projects directories are safe to be discarded and should be written to an actually temporary path.
=> test: fix path of temporary Xcode projects

CHANGELOG.md, src/nuxt/sdk-setup.ts
Adds more try/catches around each step of modifying the Nuxt config. Each step fails by setting appropriate tags and displays an error message in the output.
=> feat(nuxt): More granular error catching while modifying config

src/utils/clack-utils.ts, test/utils/clack-utils.test.ts
Distinguish the txn status based on the status code the process exits with when `abort` is called:
- `'cancelled'` doesn't increase the `failureRate()` shown in the Sentry UI
- `'aborted'` increases the failure rate (see: https://docs.sentry.io/product/insights/overview/metrics/#failure-rate)
=> telemetry: Set transaction status based on status code when aborting

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/nuxt/sdk-setup.ts, src/remix/remix-wizard.ts, src/sveltekit/sdk-setup.ts
Renames the replay feature from "Sentry Session Replay" to "Session Replay"
closes #846
=> ref: Reword Replay feature selection

CHANGELOG.md, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/utils/detect-tool.ts
These frameworks have their own wizards, being able to run them from the sourcemaps wizard is not a flow we intend to suggest to users.
Closes: #812
=> feat(sourcemaps): Remove NextJS and Remix flows from sourcemaps wizard

CHANGELOG.md, e2e-tests/tests/nextjs-14.test.ts, e2e-tests/tests/nextjs-15.test.ts, src/nextjs/nextjs-wizard.ts, src/nextjs/templates.ts, test/nextjs/templates.test.ts
We are seeing the react component annotation feature cause a lot of opaque breakage in user's applications (2+ issues/comments a week about it). It is often a hard blocker for user's that is extremely hard to debug.
We are removing the plugin for the wizard to reduce the risk of people breaking their applicaitons during Sentry setup.
=> feat(nextjs): Remove react component annotation prompt and insertion

CHANGELOG.md, src/utils/clack-utils.ts, src/utils/package-manager.ts, test/utils/clack-utils.test.ts
This PR refactors our `installPackage` helper to use `spawn` instead of `exec`. While using spawn is a bit more complicated, it gives us finer control over the the child process lifecycle as well as runtime. This is primarily made because I want to attempt fixing #851.
Additionally, we now send an error to Sentry  when this happens to keep track how often this would occur. Previously, such errors weren't captured by Sentry since we try/caught the promise rejection. 
I'll open another follow-up PR to split up the `clack-utils` file. This thing has become huge and no longer is easy to maintain.
=> ref(clack-utils): Use `child_process` `spawn` instead of `exec` when installing package

src/utils/clack-utils.ts
just a small oversight as I missed a commiting a change for a review comment in #859 and the last change made JSON stringification obsolete all together
=> ref(clack-utils): Simplify installation log file writing

src/react-native/xcode.ts, src/remix/codemods/handle-error.ts, src/remix/sdk-setup.ts, src/telemetry.ts, src/utils/clack-utils.ts, test/apple/cocoapod.test.ts, test/apple/fastfile.test.ts, test/apple/xcode-manager.test.ts, test/utils/clack-utils.test.ts
We have far too many eslint warnings in the wizard repo. Most of these are easily fixable, so let's fix them. 
Goal: Treat eslint warnings as errors so that we don't get into this state again.
This PR is a first part of this initiative, containing around 25 eslint warning fixes. We'll gradually fix all warnigns over time.
Note: Most of these PRs will contain codecov warnings about coverage. I do think we should increase coverage but this is out of scope for the lint refactors (though we can of course always throw in tests if appropriate). So I'll largely ignore codecov in these PRs. 
ref: #868
=> ref(eslint): Fix eslint warnings (part 1)

src/flutter/templates.ts
Using a more specific error gives better results in issue titles for Flutter instead of the generic exception.
=> flutter: update error snippet

.eslintrc.js, lib/Helper/File.ts, src/telemetry.ts
Two rules in one because `no-unsafe-return` required no changes as the only violation is already fixed in #870.
closes #875 
closes #876
=> ref(eslint): Set `no-unsafe-return` and `no-var-requires` to `error` 

.eslintrc.js, lib/Steps/Integrations/Cordova.ts, types/xcode.d.ts
This surfaced some weird type issue in the cordova wizard (see comment)
closes #870
=> ref(eslint): Set `@typescript-eslint/no-unsafe-call` to `error`

CHANGELOG.md, src/nextjs/templates.ts
Redesign the example page for NextJS.
Deployed a preview here:
https://next-js-sentry-xi.vercel.app/sentry-example-page
Note:
Once https://github.com/getsentry/sentry-javascript/issues/15780 is done, I will revisit this and show the adblocker warning only when needed.
- part of https://github.com/getsentry/sentry-wizard/issues/843
=> feat(next-js): New NextJS example page

CHANGELOG.md, lib/Helper/Logging.ts, src/run.ts
- Discussed this with @Lms24 in-person.
- Adds a deprecation warning for the `debug(...)` logging helper
- Enables debug logging if `--debug` is set. Currently only works for the legacy integrations.
=> fix: enable debug logs for option --debug

CHANGELOG.md, src/sveltekit/templates.ts
Redesign the example page for Sveltekit
https://github.com/user-attachments/assets/344750e8-58cf-43dd-8392-e31666cf2daa
Note:
Once https://github.com/getsentry/sentry-javascript/issues/15780 is done, I will revisit this and show the adblocker warning only when needed.
- part of https://github.com/getsentry/sentry-wizard/issues/843
=> feat(sveltekit): New example page

src/apple/apple-wizard.ts, src/apple/check-installed-cli.ts
Derived from #903 for easier review.
This is one of multiple commits to refactor the apple wizard into individual steps with the goal of improving maintainability and testability further down the line.
=> refactor(apple): move check-installed-cli to separate file

src/apple/apple-wizard.ts, src/apple/configure-fastlane.ts
Derived from https://github.com/getsentry/sentry-wizard/pull/903 for easier review.
This is one of multiple commits to refactor the apple wizard into individual steps with the goal of improving maintainability and testability further down the line.
=> refactor(apple): move configure fastlane to separate file

e2e-tests/utils/index.ts
The e2e test runs actually skew our collected telemetry data quite a lot (~10% of runs last week were from e2e tests). Let's disable telemetry collection for e2e tests.
=> test(e2e): Disable telemetry collection in e2e tests

.eslintrc.js, bin.ts, lib/Constants.ts, lib/Helper/Logging.ts, lib/Steps/BaseStep.ts, lib/Steps/Integrations/Cordova.ts
depends on #919 
explicitly sets `no-explicit-any` to `error`. Some `any`s are ignored but these are mainly in magicast code where this ProxifiedModule thing is impossible tp type correctly.
closes #920
=> ref(eslint): Set `no-explicit-any` to `error`

CHANGELOG.md
The `deno` was not included in the 4.6.0 release, move it to unreleased
=> Move deno package-manager to unreleased

.eslintrc.js, e2e-tests/tests/flutter.test.ts, e2e-tests/tests/nextjs-14.test.ts, e2e-tests/tests/nextjs-15.test.ts, e2e-tests/tests/remix.test.ts, e2e-tests/tests/sveltekit.test.ts
This PR also removes a couple of eslint-ignores in favour of explicitly declaring our custom `check*` functions in our e2e tests as assertion function names
closes #921 
=> ref(eslint): Set `jest/expect-expect` from `warn` to `error`

.github/workflows/build.yml, bin.ts, e2e-tests/tests/help-message.test.ts
We have a bunch of `preSelectedProject.*` CLI args which are only meant to bypass authentication and project selection in our e2e tests. These are not meant to be user-facing, so this PR removes them from the output of out `--help` command.
This also adds a snapshot test against the `--help` output, so that we're aware if something changes (and think twice if e.g. a newly added option should be user-facing.
=> ref: Hide e2e test args in `--help` command

CHANGELOG.md, src/nextjs/templates.ts, test/nextjs/templates.test.ts
This is necessary for routing instrumentation to work.
=> feat(nextjs): Add `onRouterTransitionStart` to client instrumentation template

lib/Setup.ts, lib/Steps/Welcome.ts, src/run.ts
This PR adds very basic telemetry collection to Electron and Cordova wizards. This doesn't add most of the tags we collect in other wizards but it should be good enough to at least get an idea of usage of these two wizards. Which is the main thing we're interested in.
=> telemetry: Add basic telemetry for electron and cordova wizards

CHANGELOG.md, src/nextjs/templates.ts
- Add error classes for the example errors
- Add some context that one is raised on the frontend, and one on the backend to educate about full stack support
Before:
After:
=> feat(nextjs): make errors on example page more useful

CHANGELOG.md, e2e-tests/tests/remix.test.ts, src/remix/sdk-setup.ts, test/remix/client-entry.test.ts
Closes https://linear.app/getsentry/issue/TET-74/[remix]-linting-errors-in-default-project-after-wizard
=> fix(remix): linting issues in generated client init code

e2e-tests/tests/angular-17.test.ts, e2e-tests/tests/angular-19.test.ts, e2e-tests/utils/index.ts, src/angular/codemods/sourcemaps.ts, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/angular.ts, src/sourcemaps/tools/sentry-cli.ts
While working on #953, I noticed that our source map generation flow has some bugs that we should fix:
- avoid crash when reading `angular.json` fails
- fixed bug where we'd remove production config in `angular.json`
- added reporting of read/write file errors to Sentry
- added a bunch of tests for `angular.json` manipulation
- fixed a bunch of lint and TS errors by introducing a defensively typed `PartialAngularJson` type
=> fix(angular): Fix source map generation bugs

CHANGELOG.md, src/remix/sdk-example.ts
- Uses the new diagnoseSdkConnectivity() function to check whether something is preventing data from reaching sentry https://github.com/getsentry/sentry-javascript/pull/15821
- If the connection is disturbed, call this out to the user using a banner and link to the docs explaining how to solve the issue
- Contributes to [TET-59](https://linear.app/getsentry/issue/TET-59/add-error-state-to-example-pages)
Before:
After:
=> feat(remix): add connection check to example page

CONTRIBUTING.md
The procedure basically is:
1. register the wizard as a linked project (only needs to be done once)
2. install latest official version of the wizard (this creates the correct binary in `node_modules`)
3. link the local version (binary forwards call to local version)
4. ???
5. profit
=> doc(contributing): Update package linking instructions

CHANGELOG.md, e2e-tests/tests/sveltekit.test.ts, src/sveltekit/sdk-example.ts, src/sveltekit/sveltekit-wizard.ts, src/sveltekit/templates.ts
- This aligns with the location of the page in other frameworks (consistency)
- Our onboarding tells you that the page is located at `sentry-example-page` as well:
=> fix(sveltekit): sentry example page should be at /sentry-example-page for consistency

.gitignore, e2e-tests/tests/angular-17.test.ts, e2e-tests/tests/angular-19.test.ts, src/angular/angular-wizard.ts, src/angular/example-component.ts, src/flutter/flutter-wizard.ts, src/nextjs/nextjs-wizard.ts, src/react-native/expo-metro.ts, src/react-native/expo.ts, src/react-native/javascript.ts, src/react-native/metro.ts, src/react-native/xcode.ts, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/tsc.ts, src/sourcemaps/tools/vite.ts, src/sourcemaps/tools/webpack.ts, src/utils/clack/index.ts, test/angular/angular-wizard.test.ts, test/angular/example-component.test.ts
This PR adds an example component (inspired by the Nuxt wizard) to the WIP Angular wizard. 
In Angular, we can't easily add a new page because the routes are declared in code (as opposed to files like in NextJs/SvelteKit/etc). Finding and injecting our component there would be quite a task, so instead, we just emit a component file and tell users how to add it to one of their pages/components.
Flow:
1. wizard asks users if they want to add the component
2. by default, it will add a new file into `./src/app` (which is the default app root folder in a conventional Angular app)
3. if this folder is not present, wizard asks users to specify a path
4. wizard writes the example component file
5. wizard prompts users via a copy/paste snippet to add the component to one of their existing …
=> feat(angular): Add example component

CHANGELOG.md
Just some minor nits and had to pull out #767 from 4.7.0 as it wasn't released yet
=> chore: fix changelog for 4.8.0 release

.github/workflows/build.yml, e2e-tests/tests/angular-17.test.ts, e2e-tests/tests/angular-19.test.ts, e2e-tests/utils/index.ts
Looks like we were running into a timeout during the Sentry CLI installation, so I bumped it to the same timeout as the SDK package installation. 
Also:
- Fixed memory leak (warning) by removing `waitForOutput` listeners once the returned promise resolved/rejected
- moved wizard execution logic beneath the actual tests for better readability  
=> test(angular): Unflake Angular e2e test

CONTRIBUTING.md
somehow a [review comment](https://github.com/getsentry/sentry-wizard/pull/952#discussion_r2044697372) managed to sneak into the doc :)
=> chore(contr): Remove copied-in review comment

CHANGELOG.md, CONTRIBUTING.md, e2e-tests/tests/expo.test.ts, e2e-tests/tests/react-native.test.ts, src/android/templates.ts, src/apple/templates.ts, src/flutter/templates.ts, src/react-native/javascript.ts, test/apple/code-tools.test.ts, test/apple/templates.test.ts, test/flutter/templates.test.ts, test/react-native/javascript.test.ts
- adds `sendDefaultPii=true` to Mobile wizards:
- Android (no tests)
- Apple (unit tests)
- Flutter (unit + e2e tests)
- RN (unit + e2e tests)
Note: as mentioned in https://github.com/getsentry/sentry-wizard/issues/955#issuecomment-2847282838 we set the default value of `true` and link to the relevant docs page
fixes https://github.com/getsentry/sentry-wizard/issues/790
fixes https://github.com/getsentry/sentry-wizard/issues/956
(Flutter + RN don't have GH issues for this)
=> feat(Mobile): adds `sendDefaultPii` to Mobile wizards

CHANGELOG.md, lib/Helper/SentryCli.ts, src/utils/sentrycli-utils.ts, test/apple/configure-sentry-cli.test.ts
- Removes unused code to create `.sentryclirc`
- Fixes the path to the `.gitignore` to ignore `sentryclirc`
=> fix(apple): Use project-relative path to gitignore file

src/sourcemaps/utils/sdk-version.ts
This PR adds a couple of packages to our list of known official Sentry SDK packages. Realized while working on #824 that the cloudflare SDK as well as some others were missing and hence the sourcemaps wizard incorrectly flagged that no sentry SDK was installed 
=> fix: Add missing SDK packages to list of known SDKs

.semgrepignore
This excludes the test directories from Semgrep's scanning.
=> ci(security): exclude test directories from semgrep code scanning

CHANGELOG.md, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/wrangler.ts, src/sourcemaps/utils/detect-tool.ts, src/utils/clack/index.ts, test/sourcemaps/tools/wrangler.test.ts
This PR adds a Cloudflare Wrangler tool flow to the source maps wizard. Because wrangler doesn't allow us to inject debug ids after build and before deployment, we have to resort to our release-based legacy upload strategy. 
Therefore, this setup flow needs to do the following things:
- install Sentry CLI
- modify the `wrangler deploy` npm script to
- determine the release value from `sentry-cli releases propose-version`
- access source maps by setting the `--outdir` arg
- inject the `SENTRY_RELEASE` environment variable
- add the `--upload-source-maps` arg so that we can guarantee that source maps are emitted into the outdir
- add a `sentry:sourcemaps` npm script that  
- determines the release value from `sentry-cli releases propose-version`
- creates a new release
- uploads source maps …
=> feat(sourcemaps): Add Cloudflare Wrangler Tool Flow

CHANGELOG.md, src/nextjs/templates.ts
- Current design is a bit confusing when there is the warning about not being able to connect to sentry, but when you press the button, you get a success message.
- Grey out the button if there is a connection issue and display a clearer warning about ad blockers.
Before:
After:
Closes TET-775
=> feat(nextjs): deactivate error button when adblocker is detected in example page

CHANGELOG.md, src/remix/sdk-example.ts
Successful connection:
Blocked Connection:
Closes TET-777
=> feat(remix): deactivate error button when adblocker is detected in example page

CHANGELOG.md, e2e-tests/tests/angular-17.test.ts, e2e-tests/tests/angular-19.test.ts, src/sourcemaps/sourcemaps-wizard.ts, src/sourcemaps/tools/sentry-cli.ts, src/utils/clack/index.ts
This PR improves the build artifact detection and selection flow in the setup wizard. Key changes:
**Create React App Support:**
- ./builder is now suggested as the default build folder when using Create React App.
**Improved Build Artifact Recovery for All Packages:**
- If the user-specified build folder is not found, the wizard now offers clearer fallback options:
- Run the build command
- Re-enter the path
- Proceed without selecting a folder
- If the user chooses to run the build command:
- The command is executed, and the wizard re-checks for the build folder.
- If still not found, the wizard suggests other likely folders.
- If possible folders are found:
- The user is prompted to pick one or none
- If the user declines all suggestions, the wizard repeats the prompt with the original …
=> feat: Introduce run build command and prompts

CHANGELOG.md, e2e-tests/tests/sveltekit.test.ts, src/sveltekit/sdk-setup.ts, src/sveltekit/templates.ts, test/sveltekit/templates.test.ts
Add logs support to the SvelteKit wizard to enable sending application logs to Sentry.
resolves https://github.com/getsentry/sentry-wizard/issues/1035
=> feat(sveltekit): Add option to enable logs to be sent to Sentry

CHANGELOG.md, src/nextjs/nextjs-wizard.ts, src/nextjs/utils.ts, test/nextjs/wizard-double-wrap-prevention.test.ts
Prevents double-wrapping in MJS/TS files. The CJS content is not replaced, but appended, so there is not double-wrapping in the first place.
I also tested this in a local Next.js project.
Closes https://github.com/getsentry/sentry-wizard/issues/1007
=> fix(nextjs): Prevent double-wrapping of Next.js config

CHANGELOG.md, src/react-native/expo-metro.ts, src/react-native/metro.ts, test/react-native/expo-metro.test.ts, test/react-native/metro.test.ts
Fixes https://github.com/getsentry/sentry-wizard/issues/1046
Adds support for `metro.config.cjs` configuration files.
Note that the injected code is already by compatible with CommonJS.
=> fix(react-native): Add support for metro.config.cjs files

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/danger.yml
Inspired by https://github.com/getsentry/sentry-cocoa/pull/5838, this PR adds a concurrency config to our CI workflows (most importantly build, but decided to apply to the others as well for completeness)
- group by workflow and ref: new commits on an existing branch will cancel CI on old commits on the same exiting branch
- limit to pull request runs to ensure we still test every commit on `master`
=> chore(ci): Add concurrency config to prevent duplicate (outdated) runs

.eslintrc.js, CHANGELOG.md, e2e-tests/package.json, e2e-tests/tests/remix.test.ts, src/remix/codemods/root.ts, test/remix/fixtures/root-already-wrapped.tsx, test/remix/fixtures/root-no-error-boundary.tsx, test/remix/fixtures/root-variable-error-boundary.tsx, test/remix/fixtures/root-with-error-boundary.tsx, test/remix/fixtures/root-with-sentry-error-boundary.tsx, test/remix/root.test.ts, tsconfig.json
Fixes the bug mentioned here: https://github.com/getsentry/sentry-docs/pull/13928#issuecomment-2983070968
=> fix(remix): Wrap app with `withSentry` independently from `hasSentryContent`

CHANGELOG.md, src/react-native/react-native-wizard.ts, src/react-native/xcode.ts, test/react-native/xcode.test.ts
Fixes https://github.com/getsentry/sentry-react-native/issues/5118
Omits quotes in `with-environment.sh` parameters script in RN >= `0.81.1` (introduced in with [this change](https://github.com/facebook/react-native/pull/53194/files#diff-f54c12ea092578cc313644cb316f74e90eb246ed8b601411cfc85f55e06ffbd6L46))
=> fix(react-native): Omits quotes in with-environment.sh parameter script in RN >= 0.81.1
