- .travis.yml
- lib/Steps/Integrations/Electron.ts
- lib/__tests__/Setup.ts
> fix: Run in different node envs, Add tests, Fix node compatibility

- scripts/Electron/symbols.js
> SentryCli is not defined

- bin.ts
- lib/Helper/Env.ts
- lib/Helper/Wizard.ts
- lib/Setup.ts
- lib/__tests__/Env.ts
Fixes https://github.com/getsentry/sentry-wizard/issues/16
> fix: Read env skip connect + tests

- CHANGELOG.md
Updates the changelog for the `v1.2.1` release.
> meta: Update changelog for v1.2.1

- .github/CODEOWNERS
> iker-barriocanal codeowner

- CHANGELOG.md
Update changelog for a new release.
> meta: Update changelog

- scripts/NextJs/configs/next.config.js
Unnecessary config elements from the `next.config.js` have been removed, and some docs have been added to explain what the file is about.
> fix(nextjs): Clean and add docs to `next.config.js`

- package.json
- yarn.lock
> build: Bump dependencies

- README.md
Make sure README matches with list: https://github.com/getsentry/sentry-wizard/blob/d927d076ada674329266504e92b871da96032823/lib/Constants.ts#L2-L7
Closes https://github.com/getsentry/sentry-wizard/pull/124
> chore: Update integration list in README

- lib/Steps/Integrations/NextJs.ts
Next 12, which has just been released, includes some changes which break the SDK. As a result, for the moment we're not officially supporting it. This PR fixes the compatibility check which occurs as part of the nextjs wizard to reflect that reality. (It also simplifies the implementation of said check a bit, relying more on the `semver` library and less on manual checks.)
> ref(nextjs): Check version range rather than minimum version

- CHANGELOG.md
Update changelog for releasing `v1.2.17`.
> meta: Update changelog for v1.2.17

- CHANGELOG.md
- lib/Steps/Integrations/ReactNative.ts
- package.json
Reverts getsentry/sentry-wizard#173
> Revert "Patch React Native xcode RN 0.69"

- CHANGELOG.md
Ref https://github.com/getsentry/sentry-javascript/issues/5505
> meta: Update changelog for 2.2.1

- CHANGELOG.md
- lib/Steps/Integrations/ReactNative.ts
context:
- https://github.com/getsentry/sentry-react-native/pull/2606
Maybe this should go to v1.
> feat(react-native): Xcode plugin includes collect modules script

- CHANGELOG.md
- lib/Steps/Integrations/NextJs.ts
context:
-  for local development we're using http (http://localhost:3000)
> fix: Print localhost with `http` instead of `https`

- CHANGELOG.md
> fix(changelog): 2.5.0 Release

- .github/workflows/build.yml
- CHANGELOG.md
- lib/Helper/File.ts
- lib/Helper/SentryCli.ts
- lib/Helper/Wizard.ts
- lib/Helper/__tests__/File.ts
- lib/Helper/__tests__/SentryCli.ts
- lib/Steps/BaseStep.ts
- lib/Steps/ChooseIntegration.ts
- lib/Steps/ConfigureProject.ts
- lib/Steps/Initial.ts
- lib/Steps/Integrations/BaseIntegration.ts
- lib/Steps/Integrations/Cordova.ts
- lib/Steps/Integrations/Electron.ts
- lib/Steps/Integrations/MobileProject.ts
- lib/Steps/Integrations/NextJs.ts
- lib/Steps/Integrations/ReactNative.ts
- lib/Steps/Integrations/__tests__/ReactNative.ts
- lib/Steps/OpenSentry.ts
- lib/Steps/PromptForParameters.ts
- lib/Steps/Result.ts
- lib/Steps/SentryProjectSelector.ts
- lib/Steps/ShouldConfigure.ts
- lib/Steps/WaitForSentry.ts
- lib/Steps/Welcome.ts
- lib/__tests__/Setup.ts
- package.json
- yarn.lock
> build: Update a bunch of dev dependencies

- .eslintrc.js
- lib/Helper/MergeConfig.ts
- lib/Steps/BaseStep.ts
- lib/Steps/Initial.ts
- lib/Steps/Integrations/BaseIntegration.ts
- lib/Steps/Integrations/Cordova.ts
- lib/Steps/Integrations/Electron.ts
- lib/Steps/Integrations/MobileProject.ts
- lib/Steps/Integrations/NextJs.ts
- lib/Steps/Integrations/ReactNative.ts
- lib/Steps/Result.ts
- lib/Steps/WaitForSentry.ts
- lib/Steps/Welcome.ts
- package.json
- yarn.lock
Use own rules and fix all errors
> build(eslint): Update eslint config

- src/sveltekit/sdk-setup.ts
This PR changes the Sentry SvelteKit Vite plugin insertion to insert them at the beginning of the array rather than appending them. This is necessary for auto-wrapping to work correctly. At the moment, we cannot use the magicast `addVitePlugin` helper to do this anymore so I took the helper's logic and adjusted it to prepend the plugin.
Note: I contributed inserting a plugin at a given index to `magicast`. If the PR is accepted, we can switch back to this logic.
see https://github.com/unjs/magicast/pull/53
ref #244
> ref(sveltekit): Prepend `sentrySvelteKit` to Vite plugins array

- CHANGELOG.md
- lib/Helper/PackageManager.ts
- lib/Steps/Integrations/ReactNative.ts
Add loader when installing deps.
> fix(rn): Show loader when installing dependencies

- src/sveltekit/sveltekit-wizard.ts
- src/templates/sveltekit-templates.ts
> chore(sveltekit): Link to docs instead of Readme

- CHANGELOG.md
- bin.ts
- src/sourcemaps/sourcemaps-wizard.ts
Resolves https://github.com/getsentry/sentry-wizard/issues/293
> feat: Add empty sourcemaps wizard

- CHANGELOG.md
- bin.ts
- lib/Constants.ts
- src/nextjs/nextjs-wizard.ts
- src/sourcemaps/sourcemaps-wizard.ts
- src/sveltekit/sveltekit-wizard.ts
- src/utils/clack-utils.ts
'+ slight refactoring of project selection util
closes #298
> feat(sourcemaps): Add Login and Project Selection flow

- CHANGELOG.md
- src/sourcemaps/sourcemaps-wizard.ts
> feat(sourcemaps): Add bundler selection prompt

- CHANGELOG.md
- src/sourcemaps/sourcemaps-wizard.ts
- src/sourcemaps/tools/types.ts
- src/sourcemaps/tools/vite.ts
- src/utils/clack-utils.ts
> feat(sourcemaps): Add setup flow for Vite

- CHANGELOG.md
- bin.ts
- src/sourcemaps/sourcemaps-wizard.ts
- src/sourcemaps/tools/sentry-cli.ts
- src/telemetry.ts
- src/utils/clack-utils.ts
Adds various tags and error reporting to the execution of the sourcemaps wizard.
Resolves https://github.com/getsentry/sentry-wizard/issues/296
> feat(sourcemaps): Add telemetry

- src/sourcemaps/sourcemaps-wizard.ts
- src/sourcemaps/tools/sentry-cli.ts
- src/utils/clack-utils.ts
May or may not have passed the output of the wizard through a particular language model to improve the wording.
> ref(sourcemaps): Adjust wording

- CHANGELOG.md
- src/sourcemaps/sourcemaps-wizard.ts
- src/sourcemaps/tools/create-react-app.ts
- src/sourcemaps/tools/sentry-cli.ts
Adds a basic flow for CRA based on the sentry-cli flow.
> feat(sourcmaps): Add create-react-app option

- CHANGELOG.md
- src/sourcemaps/sourcemaps-wizard.ts
- src/utils/clack-utils.ts
This PR improves the outro message for the source maps wizard by
* Showing an example build command for the detected package manager
* Showing the URL of the selected project's issues page
ref #290
> ref(sourcemaps): Improve Outro message

- CHANGELOG.md
- src/apple/apple-wizard.ts
- src/apple/fastlane.ts
- src/apple/templates.ts
- src/apple/xcode-manager.ts
iOS wizard detects whether the user uses Fastlane and ask to add sentry_cli plugin in a lane.
_#skip-changelog_
> Feat(apple): Add Fastlane detector for iOS wizard

- CHANGELOG.md
- src/sourcemaps/sourcemaps-wizard.ts
- src/sourcemaps/utils/detect-tool.ts
> feat(sourcemaps): Provide exit path if there's no need to upload sourcemaps

- src/android/code-tools.ts
- src/android/gradle.ts
- src/android/templates.ts
> fix(android): Handle edge-cases (full packagename or no app dir)

- CHANGELOG.md
- src/android/android-wizard.ts
- src/android/gradle.ts
* Add more telemetry for the Android wizard
* Validate and ask for the gradle file if a wrong one was given in a custom build logic scenario
> enh(android): Add more telemetry

- CHANGELOG.md
- src/nextjs/nextjs-wizard.ts
- src/nextjs/templates.ts
> fix(nextjs): add selfhosted url in next.config.js

- CHANGELOG.md
- src/remix/remix-wizard.ts
- src/remix/sdk-setup.ts
- src/utils/clack-utils.ts
Resolves: https://github.com/getsentry/sentry-wizard/issues/433
Depends on: https://github.com/getsentry/sentry-javascript/pull/8985
> feat(remix): Pass `org`, `project`, `url` to `upload-sourcemaps` script.

- CHANGELOG.md
- src/remix/remix-wizard.ts
Resolves: https://github.com/getsentry/sentry-wizard/issues/419
> fix(remix): Update documentation links to the new routes.

- CHANGELOG.md
- src/nextjs/nextjs-wizard.ts
Fixes https://github.com/getsentry/sentry-wizard/issues/508
> fix(nextjs): Fix app folder lookup

- CHANGELOG.md
- src/nextjs/nextjs-wizard.ts
- src/sourcemaps/sourcemaps-wizard.ts
Solves feedback:
> Quick question. I ran through the Sentry wizard and it generated the sentryclirc file which includes the auth token. Since this file is added to the gitignore file, what do we need to do when deployed? Add environment variable?
> feat(nextjs): Add instructions on how to set auth token in CI

- CHANGELOG.md
- src/sveltekit/sveltekit-wizard.ts
follows up on #515 and adds the same confirmation logic for example page creation to SvelteKit
ref #503
> feat(sveltekit): Ask for confirmation before creating example page

- CHANGELOG.md
- src/nextjs/templates.ts
- src/remix/sdk-setup.ts
- src/sveltekit/sdk-setup.ts
- src/sveltekit/templates.ts
- ref(sveltekit): Replace `new Replay()` with `replayIntegration`
- ref(nextjs): Replace `new Replay()` with `replayIntegration`
- ref(remix): Replace `new Replay()` with `replayIntegration`
> ref: Replace `new Replay()` with `replayIntegration`

- CHANGELOG.md
- src/remix/remix-wizard.ts
- src/remix/sdk-example.ts
> feat(remix): Add example page.

- CHANGELOG.md
- src/nextjs/nextjs-wizard.ts
- src/nextjs/templates.ts
- src/sourcemaps/tools/nextjs.ts
- src/utils/clack-utils.ts
Updates the Next.js wizard for the v8 Next.js Sentry SDK api and pins the installed version to v8 by creating or instructing user to update their instrumentation hook.
> feat(nextjs): Adjust Next.js wizard for usage with v8 SDK

- CHANGELOG.md
- src/apple/xcode-manager.ts
Upload debug symbol script wont work if  `ENABLE_USER_SCRIPT_SANDBOXING` is enabled.
closes #569
> feat(Apple): Change script sandboxing to NO

- CHANGELOG.md
- lib/Steps/Integrations/Electron.ts
In v5 of the Electron SDK there are now different instructions for the main and rederer processes.
> feat: Electron v5 changes

- CHANGELOG.md
- src/nextjs/nextjs-wizard.ts
- src/sveltekit/sdk-setup.ts
- src/sveltekit/sveltekit-wizard.ts
- src/sveltekit/templates.ts
- test/sveltekit/templates.test.ts
> feat(sveltekit): Add feature selection

- CHANGELOG.md
- src/utils/clack-utils.ts
Forward org and project slug to auth page.
Part of https://github.com/getsentry/sentry/issues/78323
> feat(wizard-ui): Forward slugs to auth page

- CHANGELOG.md
- src/nextjs/nextjs-wizard.ts
- src/utils/clack-utils.ts
Fixes https://github.com/getsentry/sentry-wizard/issues/689
> fix(nextjs): Don't ask for package manager twice

- .github/workflows/build.yml
- e2e-tests/jest.config.ts
- e2e-tests/package.json
- e2e-tests/run.sh
- e2e-tests/tsconfig.json
- package.json
Sets node version to `20.18.0` in E2E tests
Note: I'll add a README after the updates on utilities.
> test: Set node version for e2e tests.

- .github/workflows/build.yml
- e2e-tests/tests/nuxt-3.test.ts
- e2e-tests/tests/nuxt-4.test.ts
> chore(ci): Ensure Nuxt e2e tests run on ci

- src/nuxt/nuxt-wizard.ts
- src/nuxt/sdk-setup.ts
> feat(nuxt): Collect deployment platform and init-with-import-docs metric

- CHANGELOG.md
> chore(changelog): Fix incorrect PR link

- src/apple/apple-wizard.ts
- src/apple/xcode-manager.ts
> fix: Remove typo in apple-wizard and xcode-manager

- .github/CODEOWNERS
> chore(apple): add CODEOWNERS

- .github/workflows/build.yml
- e2e-tests/test-applications/angular-17-test-app/.gitignore
- e2e-tests/test-applications/angular-17-test-app/angular.json
- e2e-tests/test-applications/angular-17-test-app/package.json
- e2e-tests/test-applications/angular-17-test-app/src/app/app.component.html
- e2e-tests/test-applications/angular-17-test-app/src/app/app.component.ts
- e2e-tests/test-applications/angular-17-test-app/src/app/app.config.ts
- e2e-tests/test-applications/angular-17-test-app/src/app/app.routes.ts
- e2e-tests/test-applications/angular-17-test-app/src/index.html
- e2e-tests/test-applications/angular-17-test-app/src/main.ts
- e2e-tests/test-applications/angular-17-test-app/tsconfig.app.json
- e2e-tests/test-applications/angular-17-test-app/tsconfig.json
- e2e-tests/test-applications/angular-19-test-app/.gitignore
- e2e-tests/test-applications/angular-19-test-app/angular.json
- e2e-tests/test-applications/angular-19-test-app/package.json
- e2e-tests/test-applications/angular-19-test-app/src/app/app.component.html
- e2e-tests/test-applications/angular-19-test-app/src/app/app.component.ts
- e2e-tests/test-applications/angular-19-test-app/src/app/app.config.ts
- e2e-tests/test-applications/angular-19-test-app/src/app/app.routes.ts
- e2e-tests/test-applications/angular-19-test-app/src/index.html
- e2e-tests/test-applications/angular-19-test-app/src/main.ts
- e2e-tests/test-applications/angular-19-test-app/tsconfig.app.json
- e2e-tests/test-applications/angular-19-test-app/tsconfig.json
- e2e-tests/tests/angular-17.test.ts
- e2e-tests/tests/angular-19.test.ts
- e2e-tests/utils/index.ts
- src/angular/sdk-setup.ts
Supersedes https://github.com/getsentry/sentry-wizard/pull/741 - Tests
Targeted to the epic branch.
Adds E2E tests
Also, fixes a few overlooked changes regarding fail-returns
> test(angular): Add E2E tests.

- .github/workflows/build.yml
- .gitignore
- CHANGELOG.md
- bin.ts
- e2e-tests/test-applications/remix-test-app/package.json
- e2e-tests/tests/flutter.test.ts
- e2e-tests/tests/nextjs.test.ts
- e2e-tests/tests/nuxt-3.test.ts
- e2e-tests/tests/nuxt-4.test.ts
- e2e-tests/tests/remix.test.ts
- e2e-tests/tests/sveltekit.test.ts
- e2e-tests/utils/index.ts
- lib/Steps/OpenSentry.ts
- package.json
- src/nuxt/sdk-setup.ts
- src/utils/clack-utils.ts
- yarn.lock
The added forced resolution for `simple-plist` is to fix bundling issues
with this package that is solved in the latest version.
Context: wollardj/simple-plist#58
Fixes #758.
> feat: Add self-contained binary artifacts

- CHANGELOG.md
> meta: Update CHANGELOG for 4.0.0 release

- scripts/NextJs/configs/next.config.js
- src/nextjs/templates.ts
- test/nextjs/templates.test.ts
> docs: Update references to @sentry/webpack-plugin

- src/nextjs/nextjs-wizard.ts
nit: Just went through the flow and my package.json contained `--turbopack`, not `--turbo`.
> fix: Update turbopack notice

- CHANGELOG.md
- README.md
- lib/Constants.ts
- lib/Steps/OpenSentry.ts
- src/run.ts
- src/utils/clack-utils.ts
- src/utils/types.ts
- Part of https://github.com/getsentry/projects/issues/759
> feat: add coming-from parameter

- CHANGELOG.md
> fix: CHANGELOG.md PR 835

- src/flutter/flutter-wizard.ts
At this step, the wording confused me. I made it future tense here to make it clear the change will come and have not happened yet.
> Future tense the wizard changes

- test/flutter/templates.test.ts
I'm not sure why these tests weren't failing in the respective PR (#887) but these are currently blocking other PRs. Updated the inline snapshots to reflect the changes. Reviewers please check if the snapshots are as expected, thanks :) 
> test(flutter): Fix failing snapshot tests

- CHANGELOG.md
- lib/Steps/Integrations/Cordova.ts
- test/apple/xcode-manager.test.ts
- types/xcode.d.ts
Added additional types based on analysis of Xcode 16 projects
> fix: add additional types to xcode.d.ts

- CHANGELOG.md
- src/nextjs/templates.ts
- src/nuxt/templates.ts
Redesign the example page & component for Nuxt.
https://github.com/user-attachments/assets/02e64271-9830-45bf-beb1-5a8de1d3a30f
https://github.com/user-attachments/assets/be1095ba-b4f4-4d2b-b832-b34e5d0e7abb
Note:
Once https://github.com/getsentry/sentry-javascript/issues/15780 is done, I will revisit this and show the adblocker warning only when needed.
- part of https://github.com/getsentry/sentry-wizard/issues/843
> feat(nuxt): New example page

- CHANGELOG.md
- src/remix/sdk-example.ts
Redesign the example page & component for Nuxt.
https://github.com/user-attachments/assets/02e64271-9830-45bf-beb1-5a8de1d3a30f
- closes https://github.com/getsentry/sentry-wizard/issues/843
> feat(remix): New example page

- .eslintrc.js
- lib/Helper/Package.ts
- lib/Helper/SentryCli.ts
- lib/Helper/Wizard.ts
- lib/Helper/__tests__/SentryCli.ts
- lib/Setup.ts
- lib/Steps/Integrations/Electron.ts
- lib/Steps/PromptForParameters.ts
- lib/Types.ts
- src/nuxt/utils.ts
- src/remix/sdk-example.ts
- src/run.ts
**Note**: I left out `lib/Steps/Integrations/Cordova.ts` because I saw it being worked on in the other PR. Please feel free to take this over in my absence.
Closes: #872
Edit: converted to draft, still need to fix tests.
> ref(eslint): Set `@typescript-eslint/no-unsafe-member-access` rule to `error`

- .eslintrc.js
- e2e-tests/utils/index.ts
- lib/Helper/File.ts
- lib/Steps/Integrations/Cordova.ts
- lib/Steps/Integrations/MobileProject.ts
2 rules in one because no-unsafe-argument required exactly 1 change
closes #873 
closes #874 
> ref(eslint): Set `no-unsafe-assignment` & `no-unsage-argument` to `error`

- src/apple/templates.ts
- test/apple/templates.test.ts
> fix: apple onboarding typos

- test/react-native/xcode.test.ts
Fixes typo in xcode test https://github.com/getsentry/sentry-wizard/commit/0b075ee1aa8dbad1d2cab747cca0fa1fc648720e#r155344640
> test(react-native): Fixes typo in xcode test

- src/angular/angular-wizard.ts
Our wizard is only going to work in Angular 17 and above due to the missing NGModule AST modification for module-based Angular setups in previous versions. For now I decided that we will not bother with support for NGModules. We can revisit later. Therefore, the wizard will exit and link to the manual setup docs to avoid users going any further in the flow and risking incomplete SDK setups. 
Concrete changes:
- add a warning about unsupported Angular version for wizard-based setup and link to manual setup docs
- set a tag for this case (s.t. we can evaluate if we should extend our AST modification for older Angular versions)
- abort the wizard
Further changes:
- improved message for generally too old Angular version (older than Angular 14)
> feat(angular): Check for min compatible Angular version with wizard setup

- src/angular/angular-wizard.ts
- src/angular/sdk-setup.ts
> chore(angular): Fix typo in function name

- CHANGELOG.md
- e2e-tests/tests/flutter.test.ts
- src/flutter/code-tools.ts
- src/flutter/flutter-wizard.ts
- src/flutter/templates.ts
- test/flutter/code-tools.test.ts
- test/flutter/templates.test.ts
Closes https://github.com/getsentry/sentry-wizard/issues/826
> feat(flutter): Add replay configuration option

- CHANGELOG.md
- e2e-tests/tests/nextjs-14.test.ts
- e2e-tests/tests/nextjs-15.test.ts
- src/nextjs/nextjs-wizard.ts
- src/nextjs/templates.ts
- test/nextjs/templates.test.ts
resolves https://github.com/getsentry/sentry-wizard/issues/1030
> feat(nextjs): Add flag for enabling logs

- CHANGELOG.md
- e2e-tests/tests/angular-17.test.ts
- e2e-tests/tests/angular-19.test.ts
- src/angular/angular-wizard.ts
- src/angular/codemods/main.ts
- src/angular/sdk-setup.ts
resolves https://github.com/getsentry/sentry-wizard/issues/1032
> feat(angular): Add option to enable logs to be sent to Sentry

- CHANGELOG.md
- e2e-tests/tests/flutter.test.ts
- src/flutter/code-tools.ts
- src/flutter/templates.ts
- test/flutter/code-tools.test.ts
- test/flutter/templates.test.ts
Closes https://github.com/getsentry/sentry-wizard/issues/1038
> feat(flutter): Add structured logs opt-in

- CHANGELOG.md
- src/apple/apple-wizard.ts
- src/apple/code-tools.ts
- src/apple/inject-code-snippet.ts
- src/apple/templates.ts
- test/apple/code-tools.test.ts
- test/apple/templates.test.ts
Closes https://github.com/getsentry/sentry-cocoa/issues/5726
> feat(cocoa): Add structured logs opt-in option

- CHANGELOG.md
- src/android/android-wizard.ts
- src/android/manifest.ts
- src/android/templates.ts
Logs are now added by default to Android projects
Closes https://github.com/getsentry/sentry-wizard/issues/1037
> Add logs to Android projects
